/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PatientRecord = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'bloodType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'diagnoses' : IDL.Vec(IDL.Text),
  'lastVisit' : IDL.Int,
  'patientPrincipal' : IDL.Principal,
  'gender' : IDL.Text,
  'notes' : IDL.Text,
  'assignedDoctor' : IDL.Principal,
  'allergies' : IDL.Vec(IDL.Text),
  'riskScore' : IDL.Float64,
});
export const ModuleProgress = IDL.Record({
  'moduleId' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'artifacts' : IDL.Opt(IDL.Vec(IDL.Text)),
  'currentStep' : IDL.Nat,
  'lastSaved' : IDL.Int,
});
export const AssessmentResult = IDL.Record({
  'copingStyle' : IDL.Text,
  'baselineScore' : IDL.Float64,
  'stressTriggers' : IDL.Vec(IDL.Text),
  'personalityProfile' : IDL.Text,
  'sleepQualityScore' : IDL.Float64,
  'bigFive' : IDL.Vec(IDL.Float64),
  'stressReactivityType' : IDL.Text,
  'burnoutScore' : IDL.Float64,
  'timestamp' : IDL.Int,
  'phq9Score' : IDL.Nat,
  'gad7Score' : IDL.Nat,
});
export const AuditLogEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'actorPrincipal' : IDL.Principal,
  'targetId' : IDL.Text,
});
export const LifeGoal = IDL.Record({
  'description' : IDL.Text,
  'targetYear' : IDL.Int,
});
export const Profession = IDL.Variant({
  'musician' : IDL.Null,
  'doctor' : IDL.Null,
  'other' : IDL.Text,
  'teacher' : IDL.Null,
  'designer' : IDL.Null,
  'nurse' : IDL.Null,
  'student' : IDL.Null,
  'softwareEngineer' : IDL.Null,
  'artist' : IDL.Null,
  'scientist' : IDL.Null,
});
export const ExtendedMentalHealthProfile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'futureGoals' : IDL.Vec(LifeGoal),
  'displayName' : IDL.Text,
  'profession' : Profession,
  'anonymousMode' : IDL.Bool,
  'gender' : IDL.Int,
  'consentGiven' : IDL.Bool,
  'timeZone' : IDL.Text,
});
export const ClinicalRole = IDL.Variant({
  'patient' : IDL.Null,
  'admin' : IDL.Null,
  'doctor' : IDL.Null,
  'billing' : IDL.Null,
  'nurse' : IDL.Null,
});
export const ClinicalProfile = IDL.Record({
  'clinicalRole' : ClinicalRole,
  'principal' : IDL.Principal,
  'specialty' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'hospitalName' : IDL.Text,
  'department' : IDL.Text,
  'linkedPatients' : IDL.Vec(IDL.Principal),
});
export const DailyLog = IDL.Record({
  'id' : IDL.Text,
  'emotionTags' : IDL.Vec(IDL.Text),
  'stressRating' : IDL.Int,
  'cognitiveClarity' : IDL.Int,
  'mood' : IDL.Int,
  'productivity' : IDL.Int,
  'energyLevel' : IDL.Int,
  'timestamp' : IDL.Int,
  'sleepHours' : IDL.Float64,
});
export const PredictiveRiskFlag = IDL.Record({
  'patientId' : IDL.Text,
  'recommendations' : IDL.Vec(IDL.Text),
  'riskFactors' : IDL.Vec(IDL.Text),
  'flaggedAt' : IDL.Int,
  'severity' : IDL.Text,
  'riskScore' : IDL.Float64,
});
export const Intervention = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'endTime' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'type' : IDL.Text,
  'progress' : IDL.Float64,
  'notes' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'isReframed' : IDL.Bool,
  'cognitiveDistortions' : IDL.Vec(IDL.Text),
  'content' : IDL.Text,
  'catastrophizing' : IDL.Bool,
  'negativeBeliefs' : IDL.Bool,
  'timestamp' : IDL.Int,
  'emotionalIntensity' : IDL.Int,
  'beliefStrength' : IDL.Int,
  'socraticPrompts' : IDL.Vec(IDL.Text),
});
export const FollowUp = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'scheduledDate' : IDL.Int,
  'patientId' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'priority' : IDL.Text,
  'scheduledBy' : IDL.Principal,
  'reason' : IDL.Text,
});
export const Prescription = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'patientId' : IDL.Text,
  'icdCodes' : IDL.Vec(IDL.Text),
  'instructions' : IDL.Text,
  'medications' : IDL.Vec(
    IDL.Record({
      'duration' : IDL.Text,
      'dosage' : IDL.Text,
      'name' : IDL.Text,
      'frequency' : IDL.Text,
    })
  ),
  'doctorPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const SoapNote = IDL.Record({
  'id' : IDL.Text,
  'assessment' : IDL.Text,
  'patientId' : IDL.Text,
  'objective' : IDL.Text,
  'plan' : IDL.Text,
  'icdCodes' : IDL.Vec(IDL.Text),
  'confidenceScore' : IDL.Float64,
  'specialty' : IDL.Text,
  'doctorPrincipal' : IDL.Principal,
  'subjective' : IDL.Text,
  'timestamp' : IDL.Int,
  'voiceTranscript' : IDL.Opt(IDL.Text),
});
export const SafetyPlan = IDL.Record({
  'contacts' : IDL.Vec(IDL.Text),
  'copingStrategies' : IDL.Vec(IDL.Text),
  'crisisHotlines' : IDL.Vec(IDL.Text),
  'riskLevel' : IDL.Int,
});
export const SleepMetrics = IDL.Record({
  'sleepConsistencyScore' : IDL.Float64,
  'sleepLatency' : IDL.Float64,
  'deepSleepPercentage' : IDL.Float64,
  'averageSleepDuration' : IDL.Float64,
  'circadianRhythmScore' : IDL.Float64,
  'overallSleepHealthScore' : IDL.Float64,
  'restfulnessScore' : IDL.Float64,
  'sleepTrend' : IDL.Text,
  'remSleepPercentage' : IDL.Float64,
  'sleepEfficiency' : IDL.Float64,
});
export const RiskIndicator = IDL.Record({
  'sleepDisorderRisk' : IDL.Float64,
  'interventionRecommendations' : IDL.Vec(IDL.Text),
  'sleepImprovementEstimate' : IDL.Float64,
  'performanceImpactScore' : IDL.Float64,
  'insomniaLikelihood' : IDL.Float64,
  'moodInstabilityRisk' : IDL.Float64,
  'optimizationSuggestions' : IDL.Vec(IDL.Text),
  'burnoutRisk' : IDL.Float64,
  'potentialSleepDisruptionFactors' : IDL.Vec(IDL.Text),
  'cognitiveFatigueRisk' : IDL.Float64,
  'riskLevel' : IDL.Int,
  'projectedSleepDebt' : IDL.Float64,
});
export const NormalizedSleepInput = IDL.Record({
  'sleepConsistencyScore' : IDL.Float64,
  'screenTimeBeforeBed' : IDL.Float64,
  'sleepQualityRating' : IDL.Int,
  'bedtime' : IDL.Int,
  'sleepLatency' : IDL.Float64,
  'stressLevel' : IDL.Int,
  'napTime' : IDL.Opt(IDL.Int),
  'environmentalQualityScore' : IDL.Float64,
  'sleepPreparationRating' : IDL.Int,
  'napDuration' : IDL.Opt(IDL.Int),
  'physicalActivityIntensity' : IDL.Int,
  'wakeTime' : IDL.Int,
  'emotionalStateScore' : IDL.Int,
  'noiseLevelInSleepingArea' : IDL.Int,
  'brightnessInSleepingArea' : IDL.Int,
  'nutritionScore' : IDL.Float64,
  'substanceUseIndicator' : IDL.Bool,
  'cognitiveFatigueScore' : IDL.Int,
  'caffeineConsumption' : IDL.Float64,
  'timeZone' : IDL.Text,
  'sleepAwakeningCount' : IDL.Nat,
  'sleepDuration' : IDL.Float64,
});
export const AdvancedMetrics = IDL.Record({
  'respiratoryAnalysis' : IDL.Opt(
    IDL.Record({
      'breathingRate' : IDL.Float64,
      'co2RetentionEstimate' : IDL.Float64,
      'apneaHypopneaIndex' : IDL.Float64,
      'breathConsistency' : IDL.Float64,
      'oxygenSaturation' : IDL.Float64,
      'sleepCycleBreathCorrelation' : IDL.Float64,
    })
  ),
  'microMovementAnalysis' : IDL.Opt(
    IDL.Record({
      'movementBurstFrequency' : IDL.Float64,
      'totalSleepMovementIndex' : IDL.Float64,
      'restlessnessScore' : IDL.Float64,
      'sleepStageMovementCorrelation' : IDL.Float64,
      'movementIntensityProfile' : IDL.Float64,
    })
  ),
  'sleepArchitectureAnalysis' : IDL.Opt(
    IDL.Record({
      'sleepStageTransitions' : IDL.Vec(IDL.Nat),
      'sleepStageDurationAnalysis' : IDL.Vec(IDL.Float64),
      'sleepStageDistribution' : IDL.Vec(IDL.Float64),
      'sleepCycleCount' : IDL.Nat,
    })
  ),
  'hrvAnalysis' : IDL.Opt(
    IDL.Record({
      'fragmentIndex' : IDL.Float64,
      'meanHrv' : IDL.Float64,
      'sdnn' : IDL.Float64,
      'circadianRhythmPhase' : IDL.Float64,
      'sleepStageHrvCorrelation' : IDL.Float64,
      'rmssd' : IDL.Float64,
    })
  ),
});
export const SleepEstimatorRun = IDL.Record({
  'summaryMetrics' : SleepMetrics,
  'runTimestamp' : IDL.Int,
  'riskIndicators' : RiskIndicator,
  'audioAnalysisMetadata' : IDL.Opt(
    IDL.Record({
      'duration' : IDL.Float64,
      'audioFeatureVector' : IDL.Float64,
      'sampleRate' : IDL.Nat,
    })
  ),
  'optimizationSuggestions' : IDL.Vec(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'normalizedDailyInputs' : IDL.Vec(NormalizedSleepInput),
  'sensorDataUsed' : IDL.Opt(
    IDL.Record({
      'accelerometer' : IDL.Bool,
      'heartRateMonitor' : IDL.Bool,
      'breathingSensor' : IDL.Bool,
      'temperatureSensor' : IDL.Bool,
    })
  ),
  'daysAnalyzed' : IDL.Nat,
  'advancedMetrics' : IDL.Opt(AdvancedMetrics),
  'dataFormatVersion' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const WeeklyAnalytics = IDL.Record({
  'moodVolatility' : IDL.Float64,
  'emotionalStability' : IDL.Float64,
  'cognitiveFatigue' : IDL.Float64,
  'stressLoad' : IDL.Float64,
  'riskForecast' : IDL.Float64,
  'sleepMoodCorrelation' : IDL.Float64,
  'burnoutIndex' : IDL.Float64,
});
export const RevenueEntry = IDL.Record({
  'id' : IDL.Text,
  'source' : IDL.Text,
  'patientId' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPatientRecord' : IDL.Func([PatientRecord], [IDL.Text], []),
  'deleteSleepEstimatorRun' : IDL.Func([IDL.Nat], [], []),
  'getAllModuleProgress' : IDL.Func([], [IDL.Vec(ModuleProgress)], ['query']),
  'getAllUsersWithHighRiskFlags' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getAssessment' : IDL.Func([], [IDL.Opt(AssessmentResult)], ['query']),
  'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(ExtendedMentalHealthProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinicalProfile' : IDL.Func([], [IDL.Opt(ClinicalProfile)], ['query']),
  'getDailyLogs' : IDL.Func([], [IDL.Vec(DailyLog)], ['query']),
  'getHighRiskPatients' : IDL.Func(
      [],
      [IDL.Vec(PredictiveRiskFlag)],
      ['query'],
    ),
  'getInterventions' : IDL.Func([], [IDL.Vec(Intervention)], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getModuleProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ModuleProgress)],
      ['query'],
    ),
  'getPatientFollowUps' : IDL.Func([IDL.Text], [IDL.Vec(FollowUp)], ['query']),
  'getPatientPrescriptions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getPatientRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PatientRecord)],
      ['query'],
    ),
  'getPatientRiskFlag' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PredictiveRiskFlag)],
      ['query'],
    ),
  'getPatientSoapNotes' : IDL.Func([IDL.Text], [IDL.Vec(SoapNote)], ['query']),
  'getPrescription' : IDL.Func([IDL.Text], [IDL.Opt(Prescription)], ['query']),
  'getRevenueSummary' : IDL.Func(
      [],
      [IDL.Record({ 'total' : IDL.Float64, 'byDay' : IDL.Vec(IDL.Float64) })],
      ['query'],
    ),
  'getSafetyPlan' : IDL.Func([], [IDL.Opt(SafetyPlan)], ['query']),
  'getSleepEstimatorRunCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSleepEstimatorRuns' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(SleepEstimatorRun)],
      ['query'],
    ),
  'getSoapNote' : IDL.Func([IDL.Text], [IDL.Opt(SoapNote)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserAssessment' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AssessmentResult)],
      ['query'],
    ),
  'getUserDailyLogs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyLog)],
      ['query'],
    ),
  'getUserInterventions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Intervention)],
      ['query'],
    ),
  'getUserJournalEntries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExtendedMentalHealthProfile)],
      ['query'],
    ),
  'getUserSafetyPlan' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SafetyPlan)],
      ['query'],
    ),
  'getUserSleepEstimatorRunCount' : IDL.Func(
      [IDL.Principal],
      [IDL.Nat],
      ['query'],
    ),
  'getUserSleepEstimatorRuns' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Nat)],
      [IDL.Vec(SleepEstimatorRun)],
      ['query'],
    ),
  'getUserWeeklyAnalytics' : IDL.Func(
      [IDL.Principal],
      [WeeklyAnalytics],
      ['query'],
    ),
  'getUserWeeklyLogs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyLog)],
      ['query'],
    ),
  'getWeeklyAnalytics' : IDL.Func([], [WeeklyAnalytics], ['query']),
  'getWeeklyLogs' : IDL.Func([], [IDL.Vec(DailyLog)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listDoctorPatients' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PatientRecord)],
      ['query'],
    ),
  'recordRevenueEntry' : IDL.Func([RevenueEntry], [], []),
  'revokeConsent' : IDL.Func([], [], []),
  'saveAssessment' : IDL.Func([AssessmentResult], [], []),
  'saveCallerUserProfile' : IDL.Func([ExtendedMentalHealthProfile], [], []),
  'saveClinicalProfile' : IDL.Func([ClinicalProfile], [], []),
  'saveDailyLog' : IDL.Func([DailyLog], [], []),
  'saveFollowUp' : IDL.Func([FollowUp], [], []),
  'saveIntervention' : IDL.Func([Intervention], [], []),
  'saveJournalEntry' : IDL.Func([JournalEntry], [], []),
  'saveModuleProgress' : IDL.Func([ModuleProgress], [], []),
  'savePredictiveRiskFlag' : IDL.Func([PredictiveRiskFlag], [], []),
  'savePrescription' : IDL.Func([Prescription], [], []),
  'saveSafetyPlan' : IDL.Func([SafetyPlan], [], []),
  'saveSleepEstimatorRun' : IDL.Func([SleepEstimatorRun], [], []),
  'saveSoapNote' : IDL.Func([SoapNote], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleAnonymousMode' : IDL.Func([IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateFollowUpStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePatientRiskScore' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PatientRecord = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'bloodType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'diagnoses' : IDL.Vec(IDL.Text),
    'lastVisit' : IDL.Int,
    'patientPrincipal' : IDL.Principal,
    'gender' : IDL.Text,
    'notes' : IDL.Text,
    'assignedDoctor' : IDL.Principal,
    'allergies' : IDL.Vec(IDL.Text),
    'riskScore' : IDL.Float64,
  });
  const ModuleProgress = IDL.Record({
    'moduleId' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'artifacts' : IDL.Opt(IDL.Vec(IDL.Text)),
    'currentStep' : IDL.Nat,
    'lastSaved' : IDL.Int,
  });
  const AssessmentResult = IDL.Record({
    'copingStyle' : IDL.Text,
    'baselineScore' : IDL.Float64,
    'stressTriggers' : IDL.Vec(IDL.Text),
    'personalityProfile' : IDL.Text,
    'sleepQualityScore' : IDL.Float64,
    'bigFive' : IDL.Vec(IDL.Float64),
    'stressReactivityType' : IDL.Text,
    'burnoutScore' : IDL.Float64,
    'timestamp' : IDL.Int,
    'phq9Score' : IDL.Nat,
    'gad7Score' : IDL.Nat,
  });
  const AuditLogEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'actorPrincipal' : IDL.Principal,
    'targetId' : IDL.Text,
  });
  const LifeGoal = IDL.Record({
    'description' : IDL.Text,
    'targetYear' : IDL.Int,
  });
  const Profession = IDL.Variant({
    'musician' : IDL.Null,
    'doctor' : IDL.Null,
    'other' : IDL.Text,
    'teacher' : IDL.Null,
    'designer' : IDL.Null,
    'nurse' : IDL.Null,
    'student' : IDL.Null,
    'softwareEngineer' : IDL.Null,
    'artist' : IDL.Null,
    'scientist' : IDL.Null,
  });
  const ExtendedMentalHealthProfile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'futureGoals' : IDL.Vec(LifeGoal),
    'displayName' : IDL.Text,
    'profession' : Profession,
    'anonymousMode' : IDL.Bool,
    'gender' : IDL.Int,
    'consentGiven' : IDL.Bool,
    'timeZone' : IDL.Text,
  });
  const ClinicalRole = IDL.Variant({
    'patient' : IDL.Null,
    'admin' : IDL.Null,
    'doctor' : IDL.Null,
    'billing' : IDL.Null,
    'nurse' : IDL.Null,
  });
  const ClinicalProfile = IDL.Record({
    'clinicalRole' : ClinicalRole,
    'principal' : IDL.Principal,
    'specialty' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'hospitalName' : IDL.Text,
    'department' : IDL.Text,
    'linkedPatients' : IDL.Vec(IDL.Principal),
  });
  const DailyLog = IDL.Record({
    'id' : IDL.Text,
    'emotionTags' : IDL.Vec(IDL.Text),
    'stressRating' : IDL.Int,
    'cognitiveClarity' : IDL.Int,
    'mood' : IDL.Int,
    'productivity' : IDL.Int,
    'energyLevel' : IDL.Int,
    'timestamp' : IDL.Int,
    'sleepHours' : IDL.Float64,
  });
  const PredictiveRiskFlag = IDL.Record({
    'patientId' : IDL.Text,
    'recommendations' : IDL.Vec(IDL.Text),
    'riskFactors' : IDL.Vec(IDL.Text),
    'flaggedAt' : IDL.Int,
    'severity' : IDL.Text,
    'riskScore' : IDL.Float64,
  });
  const Intervention = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'endTime' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'type' : IDL.Text,
    'progress' : IDL.Float64,
    'notes' : IDL.Text,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'isReframed' : IDL.Bool,
    'cognitiveDistortions' : IDL.Vec(IDL.Text),
    'content' : IDL.Text,
    'catastrophizing' : IDL.Bool,
    'negativeBeliefs' : IDL.Bool,
    'timestamp' : IDL.Int,
    'emotionalIntensity' : IDL.Int,
    'beliefStrength' : IDL.Int,
    'socraticPrompts' : IDL.Vec(IDL.Text),
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'scheduledDate' : IDL.Int,
    'patientId' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'priority' : IDL.Text,
    'scheduledBy' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const Prescription = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'patientId' : IDL.Text,
    'icdCodes' : IDL.Vec(IDL.Text),
    'instructions' : IDL.Text,
    'medications' : IDL.Vec(
      IDL.Record({
        'duration' : IDL.Text,
        'dosage' : IDL.Text,
        'name' : IDL.Text,
        'frequency' : IDL.Text,
      })
    ),
    'doctorPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const SoapNote = IDL.Record({
    'id' : IDL.Text,
    'assessment' : IDL.Text,
    'patientId' : IDL.Text,
    'objective' : IDL.Text,
    'plan' : IDL.Text,
    'icdCodes' : IDL.Vec(IDL.Text),
    'confidenceScore' : IDL.Float64,
    'specialty' : IDL.Text,
    'doctorPrincipal' : IDL.Principal,
    'subjective' : IDL.Text,
    'timestamp' : IDL.Int,
    'voiceTranscript' : IDL.Opt(IDL.Text),
  });
  const SafetyPlan = IDL.Record({
    'contacts' : IDL.Vec(IDL.Text),
    'copingStrategies' : IDL.Vec(IDL.Text),
    'crisisHotlines' : IDL.Vec(IDL.Text),
    'riskLevel' : IDL.Int,
  });
  const SleepMetrics = IDL.Record({
    'sleepConsistencyScore' : IDL.Float64,
    'sleepLatency' : IDL.Float64,
    'deepSleepPercentage' : IDL.Float64,
    'averageSleepDuration' : IDL.Float64,
    'circadianRhythmScore' : IDL.Float64,
    'overallSleepHealthScore' : IDL.Float64,
    'restfulnessScore' : IDL.Float64,
    'sleepTrend' : IDL.Text,
    'remSleepPercentage' : IDL.Float64,
    'sleepEfficiency' : IDL.Float64,
  });
  const RiskIndicator = IDL.Record({
    'sleepDisorderRisk' : IDL.Float64,
    'interventionRecommendations' : IDL.Vec(IDL.Text),
    'sleepImprovementEstimate' : IDL.Float64,
    'performanceImpactScore' : IDL.Float64,
    'insomniaLikelihood' : IDL.Float64,
    'moodInstabilityRisk' : IDL.Float64,
    'optimizationSuggestions' : IDL.Vec(IDL.Text),
    'burnoutRisk' : IDL.Float64,
    'potentialSleepDisruptionFactors' : IDL.Vec(IDL.Text),
    'cognitiveFatigueRisk' : IDL.Float64,
    'riskLevel' : IDL.Int,
    'projectedSleepDebt' : IDL.Float64,
  });
  const NormalizedSleepInput = IDL.Record({
    'sleepConsistencyScore' : IDL.Float64,
    'screenTimeBeforeBed' : IDL.Float64,
    'sleepQualityRating' : IDL.Int,
    'bedtime' : IDL.Int,
    'sleepLatency' : IDL.Float64,
    'stressLevel' : IDL.Int,
    'napTime' : IDL.Opt(IDL.Int),
    'environmentalQualityScore' : IDL.Float64,
    'sleepPreparationRating' : IDL.Int,
    'napDuration' : IDL.Opt(IDL.Int),
    'physicalActivityIntensity' : IDL.Int,
    'wakeTime' : IDL.Int,
    'emotionalStateScore' : IDL.Int,
    'noiseLevelInSleepingArea' : IDL.Int,
    'brightnessInSleepingArea' : IDL.Int,
    'nutritionScore' : IDL.Float64,
    'substanceUseIndicator' : IDL.Bool,
    'cognitiveFatigueScore' : IDL.Int,
    'caffeineConsumption' : IDL.Float64,
    'timeZone' : IDL.Text,
    'sleepAwakeningCount' : IDL.Nat,
    'sleepDuration' : IDL.Float64,
  });
  const AdvancedMetrics = IDL.Record({
    'respiratoryAnalysis' : IDL.Opt(
      IDL.Record({
        'breathingRate' : IDL.Float64,
        'co2RetentionEstimate' : IDL.Float64,
        'apneaHypopneaIndex' : IDL.Float64,
        'breathConsistency' : IDL.Float64,
        'oxygenSaturation' : IDL.Float64,
        'sleepCycleBreathCorrelation' : IDL.Float64,
      })
    ),
    'microMovementAnalysis' : IDL.Opt(
      IDL.Record({
        'movementBurstFrequency' : IDL.Float64,
        'totalSleepMovementIndex' : IDL.Float64,
        'restlessnessScore' : IDL.Float64,
        'sleepStageMovementCorrelation' : IDL.Float64,
        'movementIntensityProfile' : IDL.Float64,
      })
    ),
    'sleepArchitectureAnalysis' : IDL.Opt(
      IDL.Record({
        'sleepStageTransitions' : IDL.Vec(IDL.Nat),
        'sleepStageDurationAnalysis' : IDL.Vec(IDL.Float64),
        'sleepStageDistribution' : IDL.Vec(IDL.Float64),
        'sleepCycleCount' : IDL.Nat,
      })
    ),
    'hrvAnalysis' : IDL.Opt(
      IDL.Record({
        'fragmentIndex' : IDL.Float64,
        'meanHrv' : IDL.Float64,
        'sdnn' : IDL.Float64,
        'circadianRhythmPhase' : IDL.Float64,
        'sleepStageHrvCorrelation' : IDL.Float64,
        'rmssd' : IDL.Float64,
      })
    ),
  });
  const SleepEstimatorRun = IDL.Record({
    'summaryMetrics' : SleepMetrics,
    'runTimestamp' : IDL.Int,
    'riskIndicators' : RiskIndicator,
    'audioAnalysisMetadata' : IDL.Opt(
      IDL.Record({
        'duration' : IDL.Float64,
        'audioFeatureVector' : IDL.Float64,
        'sampleRate' : IDL.Nat,
      })
    ),
    'optimizationSuggestions' : IDL.Vec(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'normalizedDailyInputs' : IDL.Vec(NormalizedSleepInput),
    'sensorDataUsed' : IDL.Opt(
      IDL.Record({
        'accelerometer' : IDL.Bool,
        'heartRateMonitor' : IDL.Bool,
        'breathingSensor' : IDL.Bool,
        'temperatureSensor' : IDL.Bool,
      })
    ),
    'daysAnalyzed' : IDL.Nat,
    'advancedMetrics' : IDL.Opt(AdvancedMetrics),
    'dataFormatVersion' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const WeeklyAnalytics = IDL.Record({
    'moodVolatility' : IDL.Float64,
    'emotionalStability' : IDL.Float64,
    'cognitiveFatigue' : IDL.Float64,
    'stressLoad' : IDL.Float64,
    'riskForecast' : IDL.Float64,
    'sleepMoodCorrelation' : IDL.Float64,
    'burnoutIndex' : IDL.Float64,
  });
  const RevenueEntry = IDL.Record({
    'id' : IDL.Text,
    'source' : IDL.Text,
    'patientId' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPatientRecord' : IDL.Func([PatientRecord], [IDL.Text], []),
    'deleteSleepEstimatorRun' : IDL.Func([IDL.Nat], [], []),
    'getAllModuleProgress' : IDL.Func([], [IDL.Vec(ModuleProgress)], ['query']),
    'getAllUsersWithHighRiskFlags' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAssessment' : IDL.Func([], [IDL.Opt(AssessmentResult)], ['query']),
    'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(ExtendedMentalHealthProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinicalProfile' : IDL.Func([], [IDL.Opt(ClinicalProfile)], ['query']),
    'getDailyLogs' : IDL.Func([], [IDL.Vec(DailyLog)], ['query']),
    'getHighRiskPatients' : IDL.Func(
        [],
        [IDL.Vec(PredictiveRiskFlag)],
        ['query'],
      ),
    'getInterventions' : IDL.Func([], [IDL.Vec(Intervention)], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getModuleProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ModuleProgress)],
        ['query'],
      ),
    'getPatientFollowUps' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FollowUp)],
        ['query'],
      ),
    'getPatientPrescriptions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getPatientRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PatientRecord)],
        ['query'],
      ),
    'getPatientRiskFlag' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PredictiveRiskFlag)],
        ['query'],
      ),
    'getPatientSoapNotes' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SoapNote)],
        ['query'],
      ),
    'getPrescription' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Prescription)],
        ['query'],
      ),
    'getRevenueSummary' : IDL.Func(
        [],
        [IDL.Record({ 'total' : IDL.Float64, 'byDay' : IDL.Vec(IDL.Float64) })],
        ['query'],
      ),
    'getSafetyPlan' : IDL.Func([], [IDL.Opt(SafetyPlan)], ['query']),
    'getSleepEstimatorRunCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSleepEstimatorRuns' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(SleepEstimatorRun)],
        ['query'],
      ),
    'getSoapNote' : IDL.Func([IDL.Text], [IDL.Opt(SoapNote)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserAssessment' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AssessmentResult)],
        ['query'],
      ),
    'getUserDailyLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyLog)],
        ['query'],
      ),
    'getUserInterventions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Intervention)],
        ['query'],
      ),
    'getUserJournalEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExtendedMentalHealthProfile)],
        ['query'],
      ),
    'getUserSafetyPlan' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SafetyPlan)],
        ['query'],
      ),
    'getUserSleepEstimatorRunCount' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getUserSleepEstimatorRuns' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Nat)],
        [IDL.Vec(SleepEstimatorRun)],
        ['query'],
      ),
    'getUserWeeklyAnalytics' : IDL.Func(
        [IDL.Principal],
        [WeeklyAnalytics],
        ['query'],
      ),
    'getUserWeeklyLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyLog)],
        ['query'],
      ),
    'getWeeklyAnalytics' : IDL.Func([], [WeeklyAnalytics], ['query']),
    'getWeeklyLogs' : IDL.Func([], [IDL.Vec(DailyLog)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listDoctorPatients' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PatientRecord)],
        ['query'],
      ),
    'recordRevenueEntry' : IDL.Func([RevenueEntry], [], []),
    'revokeConsent' : IDL.Func([], [], []),
    'saveAssessment' : IDL.Func([AssessmentResult], [], []),
    'saveCallerUserProfile' : IDL.Func([ExtendedMentalHealthProfile], [], []),
    'saveClinicalProfile' : IDL.Func([ClinicalProfile], [], []),
    'saveDailyLog' : IDL.Func([DailyLog], [], []),
    'saveFollowUp' : IDL.Func([FollowUp], [], []),
    'saveIntervention' : IDL.Func([Intervention], [], []),
    'saveJournalEntry' : IDL.Func([JournalEntry], [], []),
    'saveModuleProgress' : IDL.Func([ModuleProgress], [], []),
    'savePredictiveRiskFlag' : IDL.Func([PredictiveRiskFlag], [], []),
    'savePrescription' : IDL.Func([Prescription], [], []),
    'saveSafetyPlan' : IDL.Func([SafetyPlan], [], []),
    'saveSleepEstimatorRun' : IDL.Func([SleepEstimatorRun], [], []),
    'saveSoapNote' : IDL.Func([SoapNote], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleAnonymousMode' : IDL.Func([IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateFollowUpStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePatientRiskScore' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };