/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvancedMetrics {
  'respiratoryAnalysis' : [] | [
    {
      'breathingRate' : number,
      'co2RetentionEstimate' : number,
      'apneaHypopneaIndex' : number,
      'breathConsistency' : number,
      'oxygenSaturation' : number,
      'sleepCycleBreathCorrelation' : number,
    }
  ],
  'microMovementAnalysis' : [] | [
    {
      'movementBurstFrequency' : number,
      'totalSleepMovementIndex' : number,
      'restlessnessScore' : number,
      'sleepStageMovementCorrelation' : number,
      'movementIntensityProfile' : number,
    }
  ],
  'sleepArchitectureAnalysis' : [] | [
    {
      'sleepStageTransitions' : Array<bigint>,
      'sleepStageDurationAnalysis' : Array<number>,
      'sleepStageDistribution' : Array<number>,
      'sleepCycleCount' : bigint,
    }
  ],
  'hrvAnalysis' : [] | [
    {
      'fragmentIndex' : number,
      'meanHrv' : number,
      'sdnn' : number,
      'circadianRhythmPhase' : number,
      'sleepStageHrvCorrelation' : number,
      'rmssd' : number,
    }
  ],
}
export interface AssessmentResult {
  'copingStyle' : string,
  'baselineScore' : number,
  'stressTriggers' : Array<string>,
  'personalityProfile' : string,
  'sleepQualityScore' : number,
  'bigFive' : Array<number>,
  'stressReactivityType' : string,
  'burnoutScore' : number,
  'timestamp' : bigint,
  'phq9Score' : bigint,
  'gad7Score' : bigint,
}
export interface DailyLog {
  'id' : string,
  'emotionTags' : Array<string>,
  'stressRating' : bigint,
  'cognitiveClarity' : bigint,
  'mood' : bigint,
  'productivity' : bigint,
  'energyLevel' : bigint,
  'timestamp' : bigint,
  'sleepHours' : number,
}
export interface ExtendedMentalHealthProfile {
  'age' : [] | [bigint],
  'futureGoals' : Array<LifeGoal>,
  'displayName' : string,
  'profession' : Profession,
  'anonymousMode' : boolean,
  'gender' : bigint,
  'consentGiven' : boolean,
  'timeZone' : string,
}
export interface Intervention {
  'id' : string,
  'startTime' : bigint,
  'endTime' : [] | [bigint],
  'name' : string,
  'type' : string,
  'progress' : number,
  'notes' : string,
}
export interface JournalEntry {
  'id' : string,
  'isReframed' : boolean,
  'cognitiveDistortions' : Array<string>,
  'content' : string,
  'catastrophizing' : boolean,
  'negativeBeliefs' : boolean,
  'timestamp' : bigint,
  'emotionalIntensity' : bigint,
  'beliefStrength' : bigint,
  'socraticPrompts' : Array<string>,
}
export interface LifeGoal { 'description' : string, 'targetYear' : bigint }
export interface ModuleProgress {
  'moduleId' : string,
  'isCompleted' : boolean,
  'artifacts' : [] | [Array<string>],
  'currentStep' : bigint,
  'lastSaved' : bigint,
}
export interface NormalizedSleepInput {
  'sleepConsistencyScore' : number,
  'screenTimeBeforeBed' : number,
  'sleepQualityRating' : bigint,
  'bedtime' : bigint,
  'sleepLatency' : number,
  'stressLevel' : bigint,
  'napTime' : [] | [bigint],
  'environmentalQualityScore' : number,
  'sleepPreparationRating' : bigint,
  'napDuration' : [] | [bigint],
  'physicalActivityIntensity' : bigint,
  'wakeTime' : bigint,
  'emotionalStateScore' : bigint,
  'noiseLevelInSleepingArea' : bigint,
  'brightnessInSleepingArea' : bigint,
  'nutritionScore' : number,
  'substanceUseIndicator' : boolean,
  'cognitiveFatigueScore' : bigint,
  'caffeineConsumption' : number,
  'timeZone' : string,
  'sleepAwakeningCount' : bigint,
  'sleepDuration' : number,
}
export type Profession = { 'musician' : null } |
  { 'doctor' : null } |
  { 'other' : string } |
  { 'teacher' : null } |
  { 'designer' : null } |
  { 'nurse' : null } |
  { 'student' : null } |
  { 'softwareEngineer' : null } |
  { 'artist' : null } |
  { 'scientist' : null };
export interface RiskIndicator {
  'sleepDisorderRisk' : number,
  'interventionRecommendations' : Array<string>,
  'sleepImprovementEstimate' : number,
  'performanceImpactScore' : number,
  'insomniaLikelihood' : number,
  'moodInstabilityRisk' : number,
  'optimizationSuggestions' : Array<string>,
  'burnoutRisk' : number,
  'potentialSleepDisruptionFactors' : Array<string>,
  'cognitiveFatigueRisk' : number,
  'riskLevel' : bigint,
  'projectedSleepDebt' : number,
}
export interface SafetyPlan {
  'contacts' : Array<string>,
  'copingStrategies' : Array<string>,
  'crisisHotlines' : Array<string>,
  'riskLevel' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SleepEstimatorRun {
  'summaryMetrics' : SleepMetrics,
  'runTimestamp' : bigint,
  'riskIndicators' : RiskIndicator,
  'audioAnalysisMetadata' : [] | [
    {
      'duration' : number,
      'audioFeatureVector' : number,
      'sampleRate' : bigint,
    }
  ],
  'optimizationSuggestions' : Array<string>,
  'notes' : [] | [string],
  'normalizedDailyInputs' : Array<NormalizedSleepInput>,
  'sensorDataUsed' : [] | [
    {
      'accelerometer' : boolean,
      'heartRateMonitor' : boolean,
      'breathingSensor' : boolean,
      'temperatureSensor' : boolean,
    }
  ],
  'daysAnalyzed' : bigint,
  'advancedMetrics' : [] | [AdvancedMetrics],
  'dataFormatVersion' : string,
}
export interface SleepMetrics {
  'sleepConsistencyScore' : number,
  'sleepLatency' : number,
  'deepSleepPercentage' : number,
  'averageSleepDuration' : number,
  'circadianRhythmScore' : number,
  'overallSleepHealthScore' : number,
  'restfulnessScore' : number,
  'sleepTrend' : string,
  'remSleepPercentage' : number,
  'sleepEfficiency' : number,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyAnalytics {
  'moodVolatility' : number,
  'emotionalStability' : number,
  'cognitiveFatigue' : number,
  'stressLoad' : number,
  'riskForecast' : number,
  'sleepMoodCorrelation' : number,
  'burnoutIndex' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteSleepEstimatorRun' : ActorMethod<[bigint], undefined>,
  'getAllModuleProgress' : ActorMethod<[], Array<ModuleProgress>>,
  'getAllUsersWithHighRiskFlags' : ActorMethod<[], Array<Principal>>,
  'getAssessment' : ActorMethod<[], [] | [AssessmentResult]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [ExtendedMentalHealthProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyLogs' : ActorMethod<[], Array<DailyLog>>,
  'getInterventions' : ActorMethod<[], Array<Intervention>>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getModuleProgress' : ActorMethod<[string], [] | [ModuleProgress]>,
  'getSafetyPlan' : ActorMethod<[], [] | [SafetyPlan]>,
  'getSleepEstimatorRunCount' : ActorMethod<[], bigint>,
  'getSleepEstimatorRuns' : ActorMethod<
    [[] | [bigint]],
    Array<SleepEstimatorRun>
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserAssessment' : ActorMethod<[Principal], [] | [AssessmentResult]>,
  'getUserDailyLogs' : ActorMethod<[Principal], Array<DailyLog>>,
  'getUserInterventions' : ActorMethod<[Principal], Array<Intervention>>,
  'getUserJournalEntries' : ActorMethod<[Principal], Array<JournalEntry>>,
  'getUserProfile' : ActorMethod<
    [Principal],
    [] | [ExtendedMentalHealthProfile]
  >,
  'getUserSafetyPlan' : ActorMethod<[Principal], [] | [SafetyPlan]>,
  'getUserSleepEstimatorRunCount' : ActorMethod<[Principal], bigint>,
  'getUserSleepEstimatorRuns' : ActorMethod<
    [Principal, [] | [bigint]],
    Array<SleepEstimatorRun>
  >,
  'getUserWeeklyAnalytics' : ActorMethod<[Principal], WeeklyAnalytics>,
  'getUserWeeklyLogs' : ActorMethod<[Principal], Array<DailyLog>>,
  'getWeeklyAnalytics' : ActorMethod<[], WeeklyAnalytics>,
  'getWeeklyLogs' : ActorMethod<[], Array<DailyLog>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'revokeConsent' : ActorMethod<[], undefined>,
  'saveAssessment' : ActorMethod<[AssessmentResult], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [ExtendedMentalHealthProfile],
    undefined
  >,
  'saveDailyLog' : ActorMethod<[DailyLog], undefined>,
  'saveIntervention' : ActorMethod<[Intervention], undefined>,
  'saveJournalEntry' : ActorMethod<[JournalEntry], undefined>,
  'saveModuleProgress' : ActorMethod<[ModuleProgress], undefined>,
  'saveSafetyPlan' : ActorMethod<[SafetyPlan], undefined>,
  'saveSleepEstimatorRun' : ActorMethod<[SleepEstimatorRun], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleAnonymousMode' : ActorMethod<[boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];