import { ModuleDefinition, ModuleStep } from './moduleDefinitions';

export const ELITE_MODULE_DEFINITIONS: Record<string, ModuleDefinition> = {
  'performance-mental-rehearsal': {
    id: 'performance-mental-rehearsal',
    name: 'Performance: Mental Rehearsal',
    description: 'Visualize success to enhance performance',
    steps: [
      {
        id: 'intro',
        title: 'Mental Rehearsal',
        prompt: 'Mental rehearsal (visualization) is used by elite athletes and performers to prepare for high-stakes situations.',
        type: 'info',
      },
      {
        id: 'target-performance',
        title: 'Target Performance',
        prompt: 'What performance or situation do you want to prepare for?',
        type: 'text',
        placeholder: 'e.g., presentation, interview, competition, difficult conversation...',
      },
      {
        id: 'visualization',
        title: 'Visualization',
        prompt: 'Close your eyes. Visualize yourself performing successfully. See it in detail: what you\'re doing, how you feel, what you hear. Spend 5 minutes on this.',
        type: 'info',
        info: 'Make it vivid and multi-sensory.',
      },
      {
        id: 'key-moments',
        title: 'Key Moments',
        prompt: 'What key moments did you visualize?',
        type: 'textarea',
        placeholder: 'Describe the critical moments you rehearsed...',
      },
      {
        id: 'confidence-rating',
        title: 'Confidence Rating',
        prompt: 'How confident do you feel now about this performance?',
        type: 'slider',
        min: 0,
        max: 10,
      },
    ],
  },
  'performance-confidence-priming': {
    id: 'performance-confidence-priming',
    name: 'Performance: Confidence Priming',
    description: 'Pre-performance routines to boost self-efficacy',
    steps: [
      {
        id: 'intro',
        title: 'Confidence Priming',
        prompt: 'Confidence priming uses pre-performance rituals to activate a confident mindset.',
        type: 'info',
      },
      {
        id: 'past-success',
        title: 'Recall Past Success',
        prompt: 'Describe a time when you performed at your best:',
        type: 'textarea',
        placeholder: 'What did you do? How did you feel?',
      },
      {
        id: 'power-pose',
        title: 'Power Pose',
        prompt: 'Stand in a power pose (hands on hips, chest open) for 2 minutes. Notice how you feel.',
        type: 'info',
        info: 'Research shows this can increase confidence.',
      },
      {
        id: 'affirmation',
        title: 'Performance Affirmation',
        prompt: 'Write a short affirmation for this performance:',
        type: 'text',
        placeholder: 'e.g., "I am prepared and capable," "I trust my skills"...',
      },
      {
        id: 'pre-performance-routine',
        title: 'Pre-Performance Routine',
        prompt: 'Design a 5-minute pre-performance routine:',
        type: 'textarea',
        placeholder: 'e.g., deep breathing, power pose, affirmation, visualization...',
      },
    ],
  },
  'performance-attention-control': {
    id: 'performance-attention-control',
    name: 'Performance: Attention Control',
    description: 'Train focus and manage distractions under pressure',
    steps: [
      {
        id: 'intro',
        title: 'Attention Control',
        prompt: 'Attention control is the ability to focus on what matters and ignore distractions, especially under pressure.',
        type: 'info',
      },
      {
        id: 'focus-target',
        title: 'Focus Target',
        prompt: 'What do you need to focus on during your performance?',
        type: 'text',
        placeholder: 'e.g., the task, the audience, my breathing, the process...',
      },
      {
        id: 'distractions',
        title: 'Identify Distractions',
        prompt: 'What typically distracts you?',
        type: 'multiselect',
        options: ['Negative thoughts', 'Audience reactions', 'Mistakes', 'Time pressure', 'Physical discomfort', 'Worrying about outcome'],
      },
      {
        id: 'refocus-cue',
        title: 'Refocus Cue',
        prompt: 'Choose a cue to bring your attention back when distracted:',
        type: 'text',
        placeholder: 'e.g., "breathe," "focus," "here and now," a physical gesture...',
      },
      {
        id: 'practice-plan',
        title: 'Practice Plan',
        prompt: 'How will you practice attention control this week?',
        type: 'textarea',
        placeholder: 'e.g., meditation, focused work sessions, simulated pressure...',
      },
    ],
  },
  'burnout-recovery': {
    id: 'burnout-recovery',
    name: 'Burnout Recovery Protocol',
    description: '4-phase structured recovery from burnout',
    steps: [
      {
        id: 'intro',
        title: 'Burnout Recovery',
        prompt: 'This is a structured 4-phase protocol for recovering from burnout: Assessment → Recovery Planning → Workload Restructuring → Meaning Re-alignment.',
        type: 'info',
      },
      {
        id: 'phase1-assessment',
        title: 'Phase 1: Assessment',
        prompt: 'Rate your burnout symptoms (0-10):\nEmotional exhaustion, cynicism, reduced efficacy',
        type: 'textarea',
        placeholder: 'Describe your current burnout symptoms...',
      },
      {
        id: 'phase1-severity',
        title: 'Burnout Severity',
        prompt: 'Overall burnout severity:',
        type: 'slider',
        min: 0,
        max: 10,
      },
      {
        id: 'phase2-recovery-plan',
        title: 'Phase 2: Recovery Planning',
        prompt: 'What do you need to recover? (rest, boundaries, support, time off, etc.)',
        type: 'textarea',
        placeholder: 'List your recovery needs...',
      },
      {
        id: 'phase2-commitments',
        title: 'Recovery Commitments',
        prompt: 'What will you commit to this week for recovery?',
        type: 'checklist',
        options: ['Get 8 hours of sleep', 'Take breaks during work', 'Say no to new commitments', 'Engage in a hobby', 'Connect with support', 'Limit work hours'],
      },
      {
        id: 'phase3-workload',
        title: 'Phase 3: Workload Restructuring',
        prompt: 'What can you delegate, eliminate, or postpone?',
        type: 'textarea',
        placeholder: 'List tasks to delegate, eliminate, or postpone...',
      },
      {
        id: 'phase3-boundaries',
        title: 'Set Boundaries',
        prompt: 'What boundaries do you need to set?',
        type: 'textarea',
        placeholder: 'e.g., no work emails after 6pm, no weekend work, lunch breaks...',
      },
      {
        id: 'phase4-meaning',
        title: 'Phase 4: Meaning Re-alignment',
        prompt: 'What gives your work meaning? What values does it serve?',
        type: 'textarea',
        placeholder: 'Reconnect with the purpose of your work...',
      },
      {
        id: 'phase4-action',
        title: 'Meaningful Action',
        prompt: 'What is one action you can take to re-align with meaning?',
        type: 'text',
        placeholder: 'e.g., focus on impact, mentor someone, work on a passion project...',
      },
    ],
  },
  'trauma-grounding': {
    id: 'trauma-grounding',
    name: 'Trauma-Informed Grounding',
    description: 'Stabilization techniques and window of tolerance education',
    disclaimer: 'This module provides grounding and stabilization only. It does not process trauma. For trauma therapy, consult a qualified clinician.',
    steps: [
      {
        id: 'intro',
        title: 'Trauma-Informed Grounding',
        prompt: 'Grounding techniques help you stay present and manage overwhelming emotions. This is stabilization, not trauma processing.',
        type: 'info',
        info: 'If you are experiencing flashbacks or severe distress, please contact a mental health professional.',
      },
      {
        id: 'window-of-tolerance',
        title: 'Window of Tolerance',
        prompt: 'Your "window of tolerance" is the zone where you can function effectively. When you go outside it, you may feel hyper-aroused (anxious, panicked) or hypo-aroused (numb, shut down).',
        type: 'info',
      },
      {
        id: 'current-state',
        title: 'Current State',
        prompt: 'Where are you right now?',
        type: 'select',
        options: ['Within my window (calm, present)', 'Hyper-aroused (anxious, panicked, overwhelmed)', 'Hypo-aroused (numb, disconnected, shut down)'],
      },
      {
        id: 'grounding-technique',
        title: 'Choose a Grounding Technique',
        prompt: 'Select a technique to practice:',
        type: 'select',
        options: ['5-4-3-2-1 Senses', 'Feet on the floor', 'Cold water on hands/face', 'Name objects in the room', 'Gentle movement (stretch, walk)'],
      },
      {
        id: 'practice',
        title: 'Practice',
        prompt: 'Practice the technique now. Describe your experience:',
        type: 'textarea',
        placeholder: 'What did you notice? Did it help you feel more present?',
      },
    ],
  },
  'cbti-sleep-efficiency': {
    id: 'cbti-sleep-efficiency',
    name: 'CBT-I: Sleep Efficiency',
    description: 'Cognitive-behavioral techniques for better sleep',
    steps: [
      {
        id: 'intro',
        title: 'CBT-I: Sleep Efficiency',
        prompt: 'CBT-I (Cognitive Behavioral Therapy for Insomnia) helps you improve sleep through behavioral changes.',
        type: 'info',
      },
      {
        id: 'sleep-log',
        title: 'Sleep Log',
        prompt: 'For the past week, estimate:\nTime in bed, Time asleep, Number of awakenings',
        type: 'textarea',
        placeholder: 'Describe your sleep patterns...',
      },
      {
        id: 'time-in-bed',
        title: 'Average Time in Bed',
        prompt: 'Average hours in bed per night:',
        type: 'slider',
        min: 4,
        max: 12,
      },
      {
        id: 'time-asleep',
        title: 'Average Time Asleep',
        prompt: 'Average hours actually asleep:',
        type: 'slider',
        min: 2,
        max: 12,
      },
      {
        id: 'sleep-efficiency-calc',
        title: 'Sleep Efficiency',
        prompt: 'Sleep Efficiency = (Time Asleep / Time in Bed) × 100. A healthy sleep efficiency is 85% or higher.',
        type: 'info',
        info: 'If your efficiency is low, consider sleep restriction: reduce time in bed to match time asleep, then gradually increase.',
      },
      {
        id: 'stimulus-control',
        title: 'Stimulus Control',
        prompt: 'Commit to these rules:\n• Use bed only for sleep\n• If awake >20 min, get up\n• Go to bed only when sleepy\n• Wake at same time daily',
        type: 'checklist',
        options: ['Use bed only for sleep', 'Get up if awake >20 min', 'Go to bed only when sleepy', 'Wake at same time daily'],
      },
    ],
  },
  'habit-reversal-impulse': {
    id: 'habit-reversal-impulse',
    name: 'Habit Reversal: Impulse Control',
    description: 'Identify triggers and build replacement behaviors',
    steps: [
      {
        id: 'intro',
        title: 'Habit Reversal',
        prompt: 'Habit reversal helps you break unwanted habits by identifying triggers and building replacement behaviors.',
        type: 'info',
      },
      {
        id: 'target-habit',
        title: 'Target Habit',
        prompt: 'What habit or impulse do you want to change?',
        type: 'text',
        placeholder: 'e.g., phone checking, nail biting, procrastination, anger outbursts...',
      },
      {
        id: 'trigger-mapping',
        title: 'Trigger Mapping',
        prompt: 'When does this habit occur? What triggers it?',
        type: 'textarea',
        placeholder: 'e.g., when bored, stressed, anxious, in certain places, with certain people...',
      },
      {
        id: 'awareness-training',
        title: 'Awareness Training',
        prompt: 'Describe the early warning signs that the habit is about to happen:',
        type: 'textarea',
        placeholder: 'e.g., physical sensations, thoughts, emotions, situations...',
      },
      {
        id: 'competing-response',
        title: 'Competing Response',
        prompt: 'Choose a replacement behavior that is incompatible with the habit:',
        type: 'text',
        placeholder: 'e.g., clench fists instead of nail biting, deep breath instead of yelling...',
      },
      {
        id: 'practice-plan',
        title: 'Practice Plan',
        prompt: 'How will you practice the replacement behavior this week?',
        type: 'textarea',
        placeholder: 'Describe your plan...',
      },
    ],
  },
};
