export interface ModuleStep {
  id: string;
  title: string;
  prompt: string;
  type: 'text' | 'textarea' | 'select' | 'multiselect' | 'slider' | 'checklist' | 'info';
  options?: string[];
  min?: number;
  max?: number;
  placeholder?: string;
  info?: string;
}

export interface ModuleDefinition {
  id: string;
  name: string;
  description: string;
  disclaimer?: string;
  steps: ModuleStep[];
}

export const MODULE_DEFINITIONS: Record<string, ModuleDefinition> = {
  'act-values': {
    id: 'act-values',
    name: 'ACT: Values Clarification',
    description: 'Identify your core values and align actions with what matters most',
    steps: [
      {
        id: 'intro',
        title: 'Introduction',
        prompt: 'Values are the qualities and principles that guide your life. They are not goals to achieve, but directions to move toward.',
        type: 'info',
        info: 'This exercise will help you identify what truly matters to you.',
      },
      {
        id: 'domains',
        title: 'Life Domains',
        prompt: 'Select the life domains that are most important to you right now:',
        type: 'multiselect',
        options: ['Relationships', 'Work/Career', 'Health/Wellness', 'Personal Growth', 'Recreation', 'Spirituality', 'Community', 'Creativity'],
      },
      {
        id: 'relationships-values',
        title: 'Relationships Values',
        prompt: 'What kind of person do you want to be in your relationships?',
        type: 'textarea',
        placeholder: 'e.g., caring, honest, supportive, present...',
      },
      {
        id: 'work-values',
        title: 'Work/Career Values',
        prompt: 'What qualities do you want to bring to your work?',
        type: 'textarea',
        placeholder: 'e.g., excellence, creativity, collaboration, integrity...',
      },
      {
        id: 'committed-action',
        title: 'Committed Action',
        prompt: 'Choose one small action you can take this week that aligns with your values:',
        type: 'text',
        placeholder: 'e.g., Call a friend, volunteer 1 hour, practice a skill...',
      },
    ],
  },
  'act-defusion': {
    id: 'act-defusion',
    name: 'ACT: Cognitive Defusion',
    description: 'Learn to observe thoughts without being controlled by them',
    steps: [
      {
        id: 'intro',
        title: 'What is Cognitive Defusion?',
        prompt: 'Defusion means creating distance from your thoughts. Instead of "I am anxious," you notice "I am having the thought that I am anxious."',
        type: 'info',
      },
      {
        id: 'sticky-thought',
        title: 'Identify a Sticky Thought',
        prompt: 'What is a thought that has been bothering you lately?',
        type: 'textarea',
        placeholder: 'e.g., "I\'m not good enough," "I always fail," "Nobody likes me"...',
      },
      {
        id: 'defusion-technique',
        title: 'Choose a Defusion Technique',
        prompt: 'Select a technique to practice with this thought:',
        type: 'select',
        options: [
          'Say "I notice I\'m having the thought that..."',
          'Sing the thought to a silly tune',
          'Thank your mind for the thought',
          'Imagine the thought on a leaf floating down a stream',
          'Say the thought very slowly, word by word',
        ],
      },
      {
        id: 'practice',
        title: 'Practice',
        prompt: 'Describe your experience practicing this technique:',
        type: 'textarea',
        placeholder: 'What did you notice? Did the thought lose some of its power?',
      },
    ],
  },
  'act-committed-action': {
    id: 'act-committed-action',
    name: 'ACT: Committed Action',
    description: 'Set values-based goals and take meaningful steps forward',
    steps: [
      {
        id: 'intro',
        title: 'Committed Action',
        prompt: 'Committed action means taking steps toward what matters, even when it\'s difficult.',
        type: 'info',
      },
      {
        id: 'value',
        title: 'Choose a Value',
        prompt: 'What value do you want to act on?',
        type: 'text',
        placeholder: 'e.g., connection, growth, health, creativity...',
      },
      {
        id: 'goal',
        title: 'Set a Goal',
        prompt: 'What is a meaningful goal aligned with this value?',
        type: 'text',
        placeholder: 'e.g., reconnect with old friends, learn a new skill...',
      },
      {
        id: 'barriers',
        title: 'Identify Barriers',
        prompt: 'What obstacles might get in the way?',
        type: 'textarea',
        placeholder: 'e.g., fear of rejection, lack of time, self-doubt...',
      },
      {
        id: 'action-plan',
        title: 'Action Plan',
        prompt: 'What is one small, concrete step you can take this week?',
        type: 'text',
        placeholder: 'e.g., send one message, sign up for a class, schedule 30 minutes...',
      },
    ],
  },
  'dbt-distress-tolerance': {
    id: 'dbt-distress-tolerance',
    name: 'DBT: Distress Tolerance',
    description: 'Skills-only module for managing intense emotions without making things worse',
    disclaimer: 'This is a skills-based module, not full DBT therapy. For comprehensive DBT, consult a trained clinician.',
    steps: [
      {
        id: 'intro',
        title: 'Distress Tolerance Skills',
        prompt: 'These skills help you survive crisis moments without making things worse. They are not about fixing the problem, but getting through it safely.',
        type: 'info',
      },
      {
        id: 'crisis-level',
        title: 'Current Distress Level',
        prompt: 'Rate your current distress level:',
        type: 'slider',
        min: 0,
        max: 10,
      },
      {
        id: 'skill-selection',
        title: 'Choose a Skill',
        prompt: 'Select a distress tolerance skill to practice:',
        type: 'select',
        options: [
          'TIPP (Temperature, Intense exercise, Paced breathing, Paired muscle relaxation)',
          'Self-Soothe with 5 Senses',
          'ACCEPTS (Activities, Contributing, Comparisons, Emotions, Pushing away, Thoughts, Sensations)',
          'Radical Acceptance',
          'Distract with IMPROVE',
        ],
      },
      {
        id: 'practice',
        title: 'Practice the Skill',
        prompt: 'Describe how you practiced this skill:',
        type: 'textarea',
        placeholder: 'What did you do? What did you notice?',
      },
      {
        id: 'post-distress',
        title: 'After Practice',
        prompt: 'Rate your distress level now:',
        type: 'slider',
        min: 0,
        max: 10,
      },
    ],
  },
  'dbt-emotion-regulation': {
    id: 'dbt-emotion-regulation',
    name: 'DBT: Emotion Regulation',
    description: 'Understand and manage emotional responses effectively',
    disclaimer: 'This is a skills-based module, not full DBT therapy.',
    steps: [
      {
        id: 'intro',
        title: 'Emotion Regulation',
        prompt: 'Emotion regulation helps you understand, name, and manage your emotions more effectively.',
        type: 'info',
      },
      {
        id: 'identify-emotion',
        title: 'Identify the Emotion',
        prompt: 'What emotion are you experiencing right now?',
        type: 'select',
        options: ['Anger', 'Sadness', 'Fear', 'Joy', 'Disgust', 'Shame', 'Guilt', 'Anxiety', 'Other'],
      },
      {
        id: 'emotion-intensity',
        title: 'Emotion Intensity',
        prompt: 'How intense is this emotion?',
        type: 'slider',
        min: 0,
        max: 10,
      },
      {
        id: 'prompting-event',
        title: 'Prompting Event',
        prompt: 'What triggered this emotion?',
        type: 'textarea',
        placeholder: 'Describe the situation or event...',
      },
      {
        id: 'opposite-action',
        title: 'Opposite Action',
        prompt: 'What would opposite action look like? (Acting opposite to the emotion urge)',
        type: 'textarea',
        placeholder: 'e.g., If angry urge is to yell, opposite action is to speak calmly...',
      },
    ],
  },
  'dbt-interpersonal': {
    id: 'dbt-interpersonal',
    name: 'DBT: Interpersonal Effectiveness',
    description: 'Communicate needs and set boundaries while maintaining relationships',
    disclaimer: 'This is a skills-based module, not full DBT therapy.',
    steps: [
      {
        id: 'intro',
        title: 'Interpersonal Effectiveness',
        prompt: 'These skills help you ask for what you need, say no, and maintain self-respect in relationships.',
        type: 'info',
      },
      {
        id: 'situation',
        title: 'Describe the Situation',
        prompt: 'What interpersonal situation are you facing?',
        type: 'textarea',
        placeholder: 'e.g., Need to ask for help, set a boundary, resolve a conflict...',
      },
      {
        id: 'goal',
        title: 'Your Goal',
        prompt: 'What do you want to achieve?',
        type: 'select',
        options: [
          'Get what I want (Objective Effectiveness)',
          'Keep the relationship (Relationship Effectiveness)',
          'Keep my self-respect (Self-Respect Effectiveness)',
        ],
      },
      {
        id: 'dear-man',
        title: 'DEAR MAN Script',
        prompt: 'Use DEAR MAN to plan your communication:\nDescribe, Express, Assert, Reinforce, Mindful, Appear confident, Negotiate',
        type: 'textarea',
        placeholder: 'Write out what you will say...',
      },
    ],
  },
  'dbt-crisis-survival': {
    id: 'dbt-crisis-survival',
    name: 'DBT: Crisis Survival Skills',
    description: 'Emergency techniques for getting through crisis moments safely',
    disclaimer: 'This is a skills-based module, not full DBT therapy. In acute crisis, contact emergency services.',
    steps: [
      {
        id: 'intro',
        title: 'Crisis Survival',
        prompt: 'These are emergency skills for when you feel overwhelmed and need to get through the moment safely.',
        type: 'info',
        info: 'If you are in immediate danger, call 988 or go to your nearest emergency department.',
      },
      {
        id: 'crisis-check',
        title: 'Crisis Check',
        prompt: 'Are you in a crisis right now?',
        type: 'select',
        options: ['Yes, I need help now', 'No, I\'m planning ahead', 'Somewhat, but manageable'],
      },
      {
        id: 'tipp-skill',
        title: 'TIPP Skill',
        prompt: 'TIPP is for immediate crisis. Choose one to try:\n• Temperature (cold water on face)\n• Intense exercise (jumping jacks)\n• Paced breathing (slow, deep breaths)\n• Paired muscle relaxation',
        type: 'select',
        options: ['Temperature', 'Intense exercise', 'Paced breathing', 'Paired muscle relaxation'],
      },
      {
        id: 'practice-notes',
        title: 'Practice Notes',
        prompt: 'After practicing, note what happened:',
        type: 'textarea',
        placeholder: 'Did it help? What did you notice?',
      },
    ],
  },
  'mbct-body-scan': {
    id: 'mbct-body-scan',
    name: 'MBCT: Body Scan',
    description: 'Systematic mindfulness practice for body awareness',
    steps: [
      {
        id: 'intro',
        title: 'Body Scan Meditation',
        prompt: 'The body scan helps you develop awareness of physical sensations without judgment.',
        type: 'info',
      },
      {
        id: 'preparation',
        title: 'Preparation',
        prompt: 'Find a comfortable position (lying down or seated). Set a timer for 10-20 minutes.',
        type: 'info',
        info: 'You will systematically bring attention to each part of your body.',
      },
      {
        id: 'practice-checklist',
        title: 'Practice Checklist',
        prompt: 'Check off each body region as you scan it:',
        type: 'checklist',
        options: ['Feet', 'Lower legs', 'Upper legs', 'Hips and pelvis', 'Abdomen', 'Chest', 'Hands', 'Arms', 'Shoulders', 'Neck', 'Face', 'Top of head'],
      },
      {
        id: 'reflection',
        title: 'Reflection',
        prompt: 'What did you notice during the body scan?',
        type: 'textarea',
        placeholder: 'Sensations, thoughts, emotions, areas of tension...',
      },
    ],
  },
  'mbct-breath-anchor': {
    id: 'mbct-breath-anchor',
    name: 'MBCT: Breath Anchoring',
    description: 'Use breath as an anchor for present-moment awareness',
    steps: [
      {
        id: 'intro',
        title: 'Breath as Anchor',
        prompt: 'Your breath is always available as an anchor to the present moment.',
        type: 'info',
      },
      {
        id: 'practice-duration',
        title: 'Practice Duration',
        prompt: 'How long will you practice?',
        type: 'select',
        options: ['3 minutes', '5 minutes', '10 minutes', '15 minutes'],
      },
      {
        id: 'practice',
        title: 'Practice',
        prompt: 'Sit comfortably. Bring attention to your breath. Notice the sensation of breathing. When your mind wanders, gently return to the breath.',
        type: 'info',
        info: 'It\'s normal for the mind to wander. The practice is in noticing and returning.',
      },
      {
        id: 'reflection',
        title: 'Reflection',
        prompt: 'How many times did you notice your mind wandering?',
        type: 'slider',
        min: 0,
        max: 20,
      },
      {
        id: 'notes',
        title: 'Notes',
        prompt: 'Any observations?',
        type: 'textarea',
        placeholder: 'What was easy? What was challenging?',
      },
    ],
  },
  'mbct-urge-surfing': {
    id: 'mbct-urge-surfing',
    name: 'MBCT: Urge Surfing',
    description: 'Ride out cravings and impulses without acting on them',
    steps: [
      {
        id: 'intro',
        title: 'Urge Surfing',
        prompt: 'Urges are like waves—they rise, peak, and fall. You can ride them without acting on them.',
        type: 'info',
      },
      {
        id: 'identify-urge',
        title: 'Identify the Urge',
        prompt: 'What urge or craving are you experiencing?',
        type: 'text',
        placeholder: 'e.g., to check phone, eat junk food, avoid a task...',
      },
      {
        id: 'urge-intensity-before',
        title: 'Urge Intensity (Before)',
        prompt: 'Rate the intensity of the urge right now:',
        type: 'slider',
        min: 0,
        max: 10,
      },
      {
        id: 'surf-practice',
        title: 'Surf the Urge',
        prompt: 'Notice where you feel the urge in your body. Observe it with curiosity. Breathe. Watch it rise and fall without acting on it.',
        type: 'info',
        info: 'Practice for 3-5 minutes.',
      },
      {
        id: 'urge-intensity-after',
        title: 'Urge Intensity (After)',
        prompt: 'Rate the intensity of the urge now:',
        type: 'slider',
        min: 0,
        max: 10,
      },
    ],
  },
  'mbct-decentering': {
    id: 'mbct-decentering',
    name: 'MBCT: Cognitive Decentering',
    description: 'Observe thoughts as mental events, not facts',
    steps: [
      {
        id: 'intro',
        title: 'Cognitive Decentering',
        prompt: 'Decentering means seeing thoughts as mental events, not facts about reality.',
        type: 'info',
      },
      {
        id: 'thought',
        title: 'Identify a Thought',
        prompt: 'What thought are you having?',
        type: 'textarea',
        placeholder: 'e.g., "I\'m going to fail," "Nobody cares about me"...',
      },
      {
        id: 'reframe',
        title: 'Reframe as Mental Event',
        prompt: 'Now reframe it: "I am having the thought that..."',
        type: 'text',
        placeholder: 'I am having the thought that...',
      },
      {
        id: 'observation',
        title: 'Observe',
        prompt: 'Notice the thought without judging it or trying to change it. Just observe.',
        type: 'info',
        info: 'Thoughts are not facts. They are mental events that come and go.',
      },
      {
        id: 'reflection',
        title: 'Reflection',
        prompt: 'What did you notice when you observed the thought this way?',
        type: 'textarea',
        placeholder: 'Did it feel different? Less powerful?',
      },
    ],
  },
  'mct-rumination': {
    id: 'mct-rumination',
    name: 'MCT: Rumination Reduction',
    description: 'Break the cycle of repetitive negative thinking',
    steps: [
      {
        id: 'intro',
        title: 'Rumination',
        prompt: 'Rumination is repetitive thinking about problems, causes, and consequences. It keeps you stuck.',
        type: 'info',
      },
      {
        id: 'rumination-topic',
        title: 'What Are You Ruminating About?',
        prompt: 'What topic keeps looping in your mind?',
        type: 'textarea',
        placeholder: 'e.g., a mistake I made, a conflict, uncertainty about the future...',
      },
      {
        id: 'rumination-duration',
        title: 'How Long Have You Been Ruminating?',
        prompt: 'Estimate how long you\'ve been thinking about this:',
        type: 'select',
        options: ['Less than 1 hour', '1-3 hours', '3-6 hours', 'All day', 'Multiple days'],
      },
      {
        id: 'postpone-rumination',
        title: 'Postpone Rumination',
        prompt: 'Set a specific time later today (e.g., 7pm) to think about this for 15 minutes. For now, let it go.',
        type: 'text',
        placeholder: 'I will think about this at...',
      },
      {
        id: 'redirect',
        title: 'Redirect Attention',
        prompt: 'What will you do right now instead?',
        type: 'text',
        placeholder: 'e.g., go for a walk, call a friend, work on a task...',
      },
    ],
  },
  'mct-worry-postponement': {
    id: 'mct-worry-postponement',
    name: 'MCT: Worry Postponement',
    description: 'Schedule worry time to reduce constant anxiety',
    steps: [
      {
        id: 'intro',
        title: 'Worry Postponement',
        prompt: 'Instead of worrying all day, schedule a specific "worry time" to contain it.',
        type: 'info',
      },
      {
        id: 'worry-list',
        title: 'List Your Worries',
        prompt: 'What are you worried about right now?',
        type: 'textarea',
        placeholder: 'List all your current worries...',
      },
      {
        id: 'schedule-worry-time',
        title: 'Schedule Worry Time',
        prompt: 'Choose a 15-minute window later today to worry:',
        type: 'text',
        placeholder: 'e.g., 6:00pm - 6:15pm',
      },
      {
        id: 'commitment',
        title: 'Commitment',
        prompt: 'Commit to postponing worry until that time. If worries arise before then, remind yourself: "I\'ll think about this at 6pm."',
        type: 'info',
      },
    ],
  },
  'mct-detached-mindfulness': {
    id: 'mct-detached-mindfulness',
    name: 'MCT: Detached Mindfulness',
    description: 'Observe thoughts without engaging or suppressing them',
    steps: [
      {
        id: 'intro',
        title: 'Detached Mindfulness',
        prompt: 'Detached mindfulness means observing thoughts without analyzing, engaging, or trying to control them.',
        type: 'info',
      },
      {
        id: 'thought-stream',
        title: 'Observe Your Thought Stream',
        prompt: 'Sit quietly for 3 minutes. Notice thoughts as they arise. Don\'t engage with them—just watch them pass.',
        type: 'info',
        info: 'Imagine thoughts as clouds drifting across the sky.',
      },
      {
        id: 'practice-notes',
        title: 'Practice Notes',
        prompt: 'What did you notice?',
        type: 'textarea',
        placeholder: 'Were you able to observe without engaging? What was challenging?',
      },
    ],
  },
  'cft-self-compassion': {
    id: 'cft-self-compassion',
    name: 'CFT: Self-Compassion Scripts',
    description: 'Develop a kinder, more supportive inner voice',
    steps: [
      {
        id: 'intro',
        title: 'Self-Compassion',
        prompt: 'Self-compassion means treating yourself with the same kindness you would offer a good friend.',
        type: 'info',
      },
      {
        id: 'difficult-situation',
        title: 'Identify a Difficult Situation',
        prompt: 'What situation is causing you distress?',
        type: 'textarea',
        placeholder: 'Describe the situation...',
      },
      {
        id: 'self-criticism',
        title: 'Notice Self-Criticism',
        prompt: 'What is your inner critic saying?',
        type: 'textarea',
        placeholder: 'e.g., "You\'re so stupid," "You always mess up"...',
      },
      {
        id: 'compassionate-response',
        title: 'Compassionate Response',
        prompt: 'What would you say to a friend in this situation? Now say it to yourself:',
        type: 'textarea',
        placeholder: 'Write a compassionate response to yourself...',
      },
    ],
  },
  'cft-inner-critic': {
    id: 'cft-inner-critic',
    name: 'CFT: Inner Critic Reframe',
    description: 'Transform harsh self-criticism into constructive self-support',
    steps: [
      {
        id: 'intro',
        title: 'Inner Critic Reframe',
        prompt: 'Your inner critic often tries to protect you, but does so harshly. We can reframe it into a supportive voice.',
        type: 'info',
      },
      {
        id: 'critic-message',
        title: 'Inner Critic Message',
        prompt: 'What is your inner critic saying?',
        type: 'textarea',
        placeholder: 'e.g., "You\'re not good enough," "You\'ll never succeed"...',
      },
      {
        id: 'critic-intention',
        title: 'Critic\'s Intention',
        prompt: 'What might your inner critic be trying to protect you from?',
        type: 'textarea',
        placeholder: 'e.g., failure, rejection, disappointment...',
      },
      {
        id: 'reframe',
        title: 'Reframe',
        prompt: 'Rewrite the message in a supportive, encouraging way:',
        type: 'textarea',
        placeholder: 'e.g., "I\'m learning and growing. It\'s okay to make mistakes."',
      },
    ],
  },
  'cft-compassion-imagery': {
    id: 'cft-compassion-imagery',
    name: 'CFT: Compassion Imagery',
    description: 'Use visualization to cultivate self-compassion',
    steps: [
      {
        id: 'intro',
        title: 'Compassion Imagery',
        prompt: 'Visualization can help you access feelings of warmth, safety, and compassion.',
        type: 'info',
      },
      {
        id: 'safe-place',
        title: 'Imagine a Safe Place',
        prompt: 'Describe a place where you feel safe and calm:',
        type: 'textarea',
        placeholder: 'e.g., a beach, a forest, a cozy room...',
      },
      {
        id: 'compassionate-figure',
        title: 'Compassionate Figure',
        prompt: 'Imagine a compassionate figure (real or imagined) who embodies warmth, wisdom, and kindness. Describe them:',
        type: 'textarea',
        placeholder: 'What do they look like? How do they make you feel?',
      },
      {
        id: 'receive-compassion',
        title: 'Receive Compassion',
        prompt: 'Imagine this figure offering you compassion. What do they say to you?',
        type: 'textarea',
        placeholder: 'Write what they would say...',
      },
    ],
  },
  'sfbt-miracle-question': {
    id: 'sfbt-miracle-question',
    name: 'SFBT: Miracle Question',
    description: 'Envision your ideal future to clarify goals',
    steps: [
      {
        id: 'intro',
        title: 'The Miracle Question',
        prompt: 'Imagine that tonight, while you sleep, a miracle happens and your problems are solved. You don\'t know it happened. What would you notice tomorrow that would tell you things are better?',
        type: 'info',
      },
      {
        id: 'miracle-morning',
        title: 'The Morning After',
        prompt: 'What would be different when you wake up?',
        type: 'textarea',
        placeholder: 'How would you feel? What would you do differently?',
      },
      {
        id: 'others-notice',
        title: 'What Would Others Notice?',
        prompt: 'What would others notice about you that would tell them things are better?',
        type: 'textarea',
        placeholder: 'How would you act differently? What would they see?',
      },
      {
        id: 'small-sign',
        title: 'Small Sign',
        prompt: 'What is one small sign that the miracle has happened?',
        type: 'text',
        placeholder: 'e.g., I smile more, I reach out to friends, I feel lighter...',
      },
    ],
  },
  'sfbt-scaling': {
    id: 'sfbt-scaling',
    name: 'SFBT: Scaling Questions',
    description: 'Measure progress and identify next steps',
    steps: [
      {
        id: 'intro',
        title: 'Scaling Questions',
        prompt: 'Scaling helps you measure where you are and identify small steps forward.',
        type: 'info',
      },
      {
        id: 'current-rating',
        title: 'Current Rating',
        prompt: 'On a scale of 0-10, where 0 is the worst things have been and 10 is the best, where are you today?',
        type: 'slider',
        min: 0,
        max: 10,
      },
      {
        id: 'why-not-lower',
        title: 'Why Not Lower?',
        prompt: 'What is keeping you from being at a lower number? What are you already doing that helps?',
        type: 'textarea',
        placeholder: 'List your strengths and resources...',
      },
      {
        id: 'one-point-higher',
        title: 'One Point Higher',
        prompt: 'What would it take to move up just one point?',
        type: 'textarea',
        placeholder: 'What small change would make a difference?',
      },
    ],
  },
  'sfbt-strengths': {
    id: 'sfbt-strengths',
    name: 'SFBT: Strength Identification',
    description: 'Recognize and leverage your existing resources',
    steps: [
      {
        id: 'intro',
        title: 'Your Strengths',
        prompt: 'You already have strengths and resources that have helped you cope. Let\'s identify them.',
        type: 'info',
      },
      {
        id: 'past-success',
        title: 'Past Success',
        prompt: 'Describe a time when you successfully handled a difficult situation:',
        type: 'textarea',
        placeholder: 'What happened? How did you get through it?',
      },
      {
        id: 'strengths-list',
        title: 'Your Strengths',
        prompt: 'What strengths did you use?',
        type: 'multiselect',
        options: ['Resilience', 'Problem-solving', 'Creativity', 'Persistence', 'Social support', 'Humor', 'Flexibility', 'Courage', 'Optimism', 'Self-awareness'],
      },
      {
        id: 'apply-now',
        title: 'Apply Now',
        prompt: 'How can you use these strengths in your current situation?',
        type: 'textarea',
        placeholder: 'What would it look like to apply these strengths now?',
      },
    ],
  },
};
