/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ModuleProgress {
    moduleId: string;
    isCompleted: boolean;
    artifacts?: Array<string>;
    currentStep: bigint;
    lastSaved: bigint;
}
export interface Intervention {
    id: string;
    startTime: bigint;
    endTime?: bigint;
    name: string;
    type: string;
    progress: number;
    notes: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Profession = {
    __kind__: "musician";
    musician: null;
} | {
    __kind__: "doctor";
    doctor: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "teacher";
    teacher: null;
} | {
    __kind__: "designer";
    designer: null;
} | {
    __kind__: "nurse";
    nurse: null;
} | {
    __kind__: "student";
    student: null;
} | {
    __kind__: "softwareEngineer";
    softwareEngineer: null;
} | {
    __kind__: "artist";
    artist: null;
} | {
    __kind__: "scientist";
    scientist: null;
};
export interface WeeklyAnalytics {
    moodVolatility: number;
    emotionalStability: number;
    cognitiveFatigue: number;
    stressLoad: number;
    riskForecast: number;
    sleepMoodCorrelation: number;
    burnoutIndex: number;
}
export interface SafetyPlan {
    contacts: Array<string>;
    copingStrategies: Array<string>;
    crisisHotlines: Array<string>;
    riskLevel: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface NormalizedSleepInput {
    sleepConsistencyScore: number;
    screenTimeBeforeBed: number;
    sleepQualityRating: bigint;
    bedtime: bigint;
    sleepLatency: number;
    stressLevel: bigint;
    napTime?: bigint;
    environmentalQualityScore: number;
    sleepPreparationRating: bigint;
    napDuration?: bigint;
    physicalActivityIntensity: bigint;
    wakeTime: bigint;
    emotionalStateScore: bigint;
    noiseLevelInSleepingArea: bigint;
    brightnessInSleepingArea: bigint;
    nutritionScore: number;
    substanceUseIndicator: boolean;
    cognitiveFatigueScore: bigint;
    caffeineConsumption: number;
    timeZone: string;
    sleepAwakeningCount: bigint;
    sleepDuration: number;
}
export interface ExtendedMentalHealthProfile {
    age?: bigint;
    futureGoals: Array<LifeGoal>;
    displayName: string;
    profession: Profession;
    anonymousMode: boolean;
    gender: bigint;
    consentGiven: boolean;
    timeZone: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AdvancedMetrics {
    respiratoryAnalysis?: {
        breathingRate: number;
        co2RetentionEstimate: number;
        apneaHypopneaIndex: number;
        breathConsistency: number;
        oxygenSaturation: number;
        sleepCycleBreathCorrelation: number;
    };
    microMovementAnalysis?: {
        movementBurstFrequency: number;
        totalSleepMovementIndex: number;
        restlessnessScore: number;
        sleepStageMovementCorrelation: number;
        movementIntensityProfile: number;
    };
    sleepArchitectureAnalysis?: {
        sleepStageTransitions: Array<bigint>;
        sleepStageDurationAnalysis: Array<number>;
        sleepStageDistribution: Array<number>;
        sleepCycleCount: bigint;
    };
    hrvAnalysis?: {
        fragmentIndex: number;
        meanHrv: number;
        sdnn: number;
        circadianRhythmPhase: number;
        sleepStageHrvCorrelation: number;
        rmssd: number;
    };
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface LifeGoal {
    description: string;
    targetYear: bigint;
}
export interface JournalEntry {
    id: string;
    isReframed: boolean;
    cognitiveDistortions: Array<string>;
    content: string;
    catastrophizing: boolean;
    negativeBeliefs: boolean;
    timestamp: bigint;
    emotionalIntensity: bigint;
    beliefStrength: bigint;
    socraticPrompts: Array<string>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DailyLog {
    id: string;
    emotionTags: Array<string>;
    stressRating: bigint;
    cognitiveClarity: bigint;
    mood: bigint;
    productivity: bigint;
    energyLevel: bigint;
    timestamp: bigint;
    sleepHours: number;
}
export interface AssessmentResult {
    copingStyle: string;
    baselineScore: number;
    stressTriggers: Array<string>;
    personalityProfile: string;
    sleepQualityScore: number;
    bigFive: Array<number>;
    stressReactivityType: string;
    burnoutScore: number;
    timestamp: bigint;
    phq9Score: bigint;
    gad7Score: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SleepEstimatorRun {
    summaryMetrics: SleepMetrics;
    runTimestamp: bigint;
    riskIndicators: RiskIndicator;
    audioAnalysisMetadata?: {
        duration: number;
        audioFeatureVector: number;
        sampleRate: bigint;
    };
    optimizationSuggestions: Array<string>;
    notes?: string;
    normalizedDailyInputs: Array<NormalizedSleepInput>;
    sensorDataUsed?: {
        accelerometer: boolean;
        heartRateMonitor: boolean;
        breathingSensor: boolean;
        temperatureSensor: boolean;
    };
    daysAnalyzed: bigint;
    advancedMetrics?: AdvancedMetrics;
    dataFormatVersion: string;
}
export interface SleepMetrics {
    sleepConsistencyScore: number;
    sleepLatency: number;
    deepSleepPercentage: number;
    averageSleepDuration: number;
    circadianRhythmScore: number;
    overallSleepHealthScore: number;
    restfulnessScore: number;
    sleepTrend: string;
    remSleepPercentage: number;
    sleepEfficiency: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface RiskIndicator {
    sleepDisorderRisk: number;
    interventionRecommendations: Array<string>;
    sleepImprovementEstimate: number;
    performanceImpactScore: number;
    insomniaLikelihood: number;
    moodInstabilityRisk: number;
    optimizationSuggestions: Array<string>;
    burnoutRisk: number;
    potentialSleepDisruptionFactors: Array<string>;
    cognitiveFatigueRisk: number;
    riskLevel: bigint;
    projectedSleepDebt: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteSleepEstimatorRun(runId: bigint): Promise<void>;
    getAllModuleProgress(): Promise<Array<ModuleProgress>>;
    getAllUsersWithHighRiskFlags(): Promise<Array<Principal>>;
    getAssessment(): Promise<AssessmentResult | null>;
    getCallerUserProfile(): Promise<ExtendedMentalHealthProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyLogs(): Promise<Array<DailyLog>>;
    getInterventions(): Promise<Array<Intervention>>;
    getJournalEntries(): Promise<Array<JournalEntry>>;
    getModuleProgress(moduleId: string): Promise<ModuleProgress | null>;
    getSafetyPlan(): Promise<SafetyPlan | null>;
    getSleepEstimatorRunCount(): Promise<bigint>;
    getSleepEstimatorRuns(limit: bigint | null): Promise<Array<SleepEstimatorRun>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserAssessment(user: Principal): Promise<AssessmentResult | null>;
    getUserDailyLogs(user: Principal): Promise<Array<DailyLog>>;
    getUserInterventions(user: Principal): Promise<Array<Intervention>>;
    getUserJournalEntries(user: Principal): Promise<Array<JournalEntry>>;
    getUserProfile(user: Principal): Promise<ExtendedMentalHealthProfile | null>;
    getUserSafetyPlan(user: Principal): Promise<SafetyPlan | null>;
    getUserSleepEstimatorRunCount(user: Principal): Promise<bigint>;
    getUserSleepEstimatorRuns(user: Principal, limit: bigint | null): Promise<Array<SleepEstimatorRun>>;
    getUserWeeklyAnalytics(user: Principal): Promise<WeeklyAnalytics>;
    getUserWeeklyLogs(user: Principal): Promise<Array<DailyLog>>;
    getWeeklyAnalytics(): Promise<WeeklyAnalytics>;
    getWeeklyLogs(): Promise<Array<DailyLog>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    revokeConsent(): Promise<void>;
    saveAssessment(result: AssessmentResult): Promise<void>;
    saveCallerUserProfile(profile: ExtendedMentalHealthProfile): Promise<void>;
    saveDailyLog(dayLog: DailyLog): Promise<void>;
    saveIntervention(intervention: Intervention): Promise<void>;
    saveJournalEntry(entry: JournalEntry): Promise<void>;
    saveModuleProgress(progress: ModuleProgress): Promise<void>;
    saveSafetyPlan(plan: SafetyPlan): Promise<void>;
    saveSleepEstimatorRun(run: SleepEstimatorRun): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    toggleAnonymousMode(isAnonymous: boolean): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AdvancedMetrics as _AdvancedMetrics, AssessmentResult as _AssessmentResult, ExtendedMentalHealthProfile as _ExtendedMentalHealthProfile, Intervention as _Intervention, LifeGoal as _LifeGoal, ModuleProgress as _ModuleProgress, NormalizedSleepInput as _NormalizedSleepInput, Profession as _Profession, RiskIndicator as _RiskIndicator, SafetyPlan as _SafetyPlan, SleepEstimatorRun as _SleepEstimatorRun, SleepMetrics as _SleepMetrics, StripeSessionStatus as _StripeSessionStatus, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteSleepEstimatorRun(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSleepEstimatorRun(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSleepEstimatorRun(arg0);
            return result;
        }
    }
    async getAllModuleProgress(): Promise<Array<ModuleProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllModuleProgress();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllModuleProgress();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersWithHighRiskFlags(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithHighRiskFlags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithHighRiskFlags();
            return result;
        }
    }
    async getAssessment(): Promise<AssessmentResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessment();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessment();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<ExtendedMentalHealthProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyLogs(): Promise<Array<DailyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyLogs();
            return result;
        }
    }
    async getInterventions(): Promise<Array<Intervention>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterventions();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterventions();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries();
            return result;
        }
    }
    async getModuleProgress(arg0: string): Promise<ModuleProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getModuleProgress(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModuleProgress(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSafetyPlan(): Promise<SafetyPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafetyPlan();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafetyPlan();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSleepEstimatorRunCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSleepEstimatorRunCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSleepEstimatorRunCount();
            return result;
        }
    }
    async getSleepEstimatorRuns(arg0: bigint | null): Promise<Array<SleepEstimatorRun>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSleepEstimatorRuns(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSleepEstimatorRuns(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAssessment(arg0: Principal): Promise<AssessmentResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAssessment(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAssessment(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserDailyLogs(arg0: Principal): Promise<Array<DailyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDailyLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDailyLogs(arg0);
            return result;
        }
    }
    async getUserInterventions(arg0: Principal): Promise<Array<Intervention>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserInterventions(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserInterventions(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserJournalEntries(arg0: Principal): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserJournalEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserJournalEntries(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<ExtendedMentalHealthProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSafetyPlan(arg0: Principal): Promise<SafetyPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSafetyPlan(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSafetyPlan(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSleepEstimatorRunCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSleepEstimatorRunCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSleepEstimatorRunCount(arg0);
            return result;
        }
    }
    async getUserSleepEstimatorRuns(arg0: Principal, arg1: bigint | null): Promise<Array<SleepEstimatorRun>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSleepEstimatorRuns(arg0, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSleepEstimatorRuns(arg0, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWeeklyAnalytics(arg0: Principal): Promise<WeeklyAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWeeklyAnalytics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWeeklyAnalytics(arg0);
            return result;
        }
    }
    async getUserWeeklyLogs(arg0: Principal): Promise<Array<DailyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWeeklyLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWeeklyLogs(arg0);
            return result;
        }
    }
    async getWeeklyAnalytics(): Promise<WeeklyAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyAnalytics();
            return result;
        }
    }
    async getWeeklyLogs(): Promise<Array<DailyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyLogs();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async revokeConsent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeConsent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeConsent();
            return result;
        }
    }
    async saveAssessment(arg0: AssessmentResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAssessment(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: ExtendedMentalHealthProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_ExtendedMentalHealthProfile_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_ExtendedMentalHealthProfile_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDailyLog(arg0: DailyLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyLog(arg0);
            return result;
        }
    }
    async saveIntervention(arg0: Intervention): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIntervention(to_candid_Intervention_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIntervention(to_candid_Intervention_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveJournalEntry(arg0: JournalEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJournalEntry(arg0);
            return result;
        }
    }
    async saveModuleProgress(arg0: ModuleProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveModuleProgress(to_candid_ModuleProgress_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveModuleProgress(to_candid_ModuleProgress_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveSafetyPlan(arg0: SafetyPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSafetyPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSafetyPlan(arg0);
            return result;
        }
    }
    async saveSleepEstimatorRun(arg0: SleepEstimatorRun): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSleepEstimatorRun(to_candid_SleepEstimatorRun_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSleepEstimatorRun(to_candid_SleepEstimatorRun_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async toggleAnonymousMode(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAnonymousMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAnonymousMode(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_AdvancedMetrics_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdvancedMetrics): AdvancedMetrics {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_ExtendedMentalHealthProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtendedMentalHealthProfile): ExtendedMentalHealthProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Intervention_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Intervention): Intervention {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ModuleProgress_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModuleProgress): ModuleProgress {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_NormalizedSleepInput_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NormalizedSleepInput): NormalizedSleepInput {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Profession_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profession): Profession {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SleepEstimatorRun_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SleepEstimatorRun): SleepEstimatorRun {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssessmentResult]): AssessmentResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedMentalHealthProfile]): ExtendedMentalHealthProfile | null {
    return value.length === 0 ? null : from_candid_ExtendedMentalHealthProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ModuleProgress]): ModuleProgress | null {
    return value.length === 0 ? null : from_candid_ModuleProgress_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SafetyPlan]): SafetyPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        duration: number;
        audioFeatureVector: number;
        sampleRate: bigint;
    }]): {
    duration: number;
    audioFeatureVector: number;
    sampleRate: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        accelerometer: boolean;
        heartRateMonitor: boolean;
        breathingSensor: boolean;
        temperatureSensor: boolean;
    }]): {
    accelerometer: boolean;
    heartRateMonitor: boolean;
    breathingSensor: boolean;
    temperatureSensor: boolean;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdvancedMetrics]): AdvancedMetrics | null {
    return value.length === 0 ? null : from_candid_AdvancedMetrics_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        breathingRate: number;
        co2RetentionEstimate: number;
        apneaHypopneaIndex: number;
        breathConsistency: number;
        oxygenSaturation: number;
        sleepCycleBreathCorrelation: number;
    }]): {
    breathingRate: number;
    co2RetentionEstimate: number;
    apneaHypopneaIndex: number;
    breathConsistency: number;
    oxygenSaturation: number;
    sleepCycleBreathCorrelation: number;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        movementBurstFrequency: number;
        totalSleepMovementIndex: number;
        restlessnessScore: number;
        sleepStageMovementCorrelation: number;
        movementIntensityProfile: number;
    }]): {
    movementBurstFrequency: number;
    totalSleepMovementIndex: number;
    restlessnessScore: number;
    sleepStageMovementCorrelation: number;
    movementIntensityProfile: number;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        sleepStageTransitions: Array<bigint>;
        sleepStageDurationAnalysis: Array<number>;
        sleepStageDistribution: Array<number>;
        sleepCycleCount: bigint;
    }]): {
    sleepStageTransitions: Array<bigint>;
    sleepStageDurationAnalysis: Array<number>;
    sleepStageDistribution: Array<number>;
    sleepCycleCount: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        fragmentIndex: number;
        meanHrv: number;
        sdnn: number;
        circadianRhythmPhase: number;
        sleepStageHrvCorrelation: number;
        rmssd: number;
    }]): {
    fragmentIndex: number;
    meanHrv: number;
    sdnn: number;
    circadianRhythmPhase: number;
    sleepStageHrvCorrelation: number;
    rmssd: number;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moduleId: string;
    isCompleted: boolean;
    artifacts: [] | [Array<string>];
    currentStep: bigint;
    lastSaved: bigint;
}): {
    moduleId: string;
    isCompleted: boolean;
    artifacts?: Array<string>;
    currentStep: bigint;
    lastSaved: bigint;
} {
    return {
        moduleId: value.moduleId,
        isCompleted: value.isCompleted,
        artifacts: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.artifacts)),
        currentStep: value.currentStep,
        lastSaved: value.lastSaved
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: [] | [bigint];
    futureGoals: Array<_LifeGoal>;
    displayName: string;
    profession: _Profession;
    anonymousMode: boolean;
    gender: bigint;
    consentGiven: boolean;
    timeZone: string;
}): {
    age?: bigint;
    futureGoals: Array<LifeGoal>;
    displayName: string;
    profession: Profession;
    anonymousMode: boolean;
    gender: bigint;
    consentGiven: boolean;
    timeZone: string;
} {
    return {
        age: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.age)),
        futureGoals: value.futureGoals,
        displayName: value.displayName,
        profession: from_candid_Profession_n18(_uploadFile, _downloadFile, value.profession),
        anonymousMode: value.anonymousMode,
        gender: value.gender,
        consentGiven: value.consentGiven,
        timeZone: value.timeZone
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: bigint;
    endTime: [] | [bigint];
    name: string;
    type: string;
    progress: number;
    notes: string;
}): {
    id: string;
    startTime: bigint;
    endTime?: bigint;
    name: string;
    type: string;
    progress: number;
    notes: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.endTime)),
        name: value.name,
        type: value.type,
        progress: value.progress,
        notes: value.notes
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    summaryMetrics: _SleepMetrics;
    runTimestamp: bigint;
    riskIndicators: _RiskIndicator;
    audioAnalysisMetadata: [] | [{
            duration: number;
            audioFeatureVector: number;
            sampleRate: bigint;
        }];
    optimizationSuggestions: Array<string>;
    notes: [] | [string];
    normalizedDailyInputs: Array<_NormalizedSleepInput>;
    sensorDataUsed: [] | [{
            accelerometer: boolean;
            heartRateMonitor: boolean;
            breathingSensor: boolean;
            temperatureSensor: boolean;
        }];
    daysAnalyzed: bigint;
    advancedMetrics: [] | [_AdvancedMetrics];
    dataFormatVersion: string;
}): {
    summaryMetrics: SleepMetrics;
    runTimestamp: bigint;
    riskIndicators: RiskIndicator;
    audioAnalysisMetadata?: {
        duration: number;
        audioFeatureVector: number;
        sampleRate: bigint;
    };
    optimizationSuggestions: Array<string>;
    notes?: string;
    normalizedDailyInputs: Array<NormalizedSleepInput>;
    sensorDataUsed?: {
        accelerometer: boolean;
        heartRateMonitor: boolean;
        breathingSensor: boolean;
        temperatureSensor: boolean;
    };
    daysAnalyzed: bigint;
    advancedMetrics?: AdvancedMetrics;
    dataFormatVersion: string;
} {
    return {
        summaryMetrics: value.summaryMetrics,
        runTimestamp: value.runTimestamp,
        riskIndicators: value.riskIndicators,
        audioAnalysisMetadata: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.audioAnalysisMetadata)),
        optimizationSuggestions: value.optimizationSuggestions,
        notes: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.notes)),
        normalizedDailyInputs: from_candid_vec_n34(_uploadFile, _downloadFile, value.normalizedDailyInputs),
        sensorDataUsed: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.sensorDataUsed)),
        daysAnalyzed: value.daysAnalyzed,
        advancedMetrics: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.advancedMetrics)),
        dataFormatVersion: value.dataFormatVersion
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sleepConsistencyScore: number;
    screenTimeBeforeBed: number;
    sleepQualityRating: bigint;
    bedtime: bigint;
    sleepLatency: number;
    stressLevel: bigint;
    napTime: [] | [bigint];
    environmentalQualityScore: number;
    sleepPreparationRating: bigint;
    napDuration: [] | [bigint];
    physicalActivityIntensity: bigint;
    wakeTime: bigint;
    emotionalStateScore: bigint;
    noiseLevelInSleepingArea: bigint;
    brightnessInSleepingArea: bigint;
    nutritionScore: number;
    substanceUseIndicator: boolean;
    cognitiveFatigueScore: bigint;
    caffeineConsumption: number;
    timeZone: string;
    sleepAwakeningCount: bigint;
    sleepDuration: number;
}): {
    sleepConsistencyScore: number;
    screenTimeBeforeBed: number;
    sleepQualityRating: bigint;
    bedtime: bigint;
    sleepLatency: number;
    stressLevel: bigint;
    napTime?: bigint;
    environmentalQualityScore: number;
    sleepPreparationRating: bigint;
    napDuration?: bigint;
    physicalActivityIntensity: bigint;
    wakeTime: bigint;
    emotionalStateScore: bigint;
    noiseLevelInSleepingArea: bigint;
    brightnessInSleepingArea: bigint;
    nutritionScore: number;
    substanceUseIndicator: boolean;
    cognitiveFatigueScore: bigint;
    caffeineConsumption: number;
    timeZone: string;
    sleepAwakeningCount: bigint;
    sleepDuration: number;
} {
    return {
        sleepConsistencyScore: value.sleepConsistencyScore,
        screenTimeBeforeBed: value.screenTimeBeforeBed,
        sleepQualityRating: value.sleepQualityRating,
        bedtime: value.bedtime,
        sleepLatency: value.sleepLatency,
        stressLevel: value.stressLevel,
        napTime: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.napTime)),
        environmentalQualityScore: value.environmentalQualityScore,
        sleepPreparationRating: value.sleepPreparationRating,
        napDuration: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.napDuration)),
        physicalActivityIntensity: value.physicalActivityIntensity,
        wakeTime: value.wakeTime,
        emotionalStateScore: value.emotionalStateScore,
        noiseLevelInSleepingArea: value.noiseLevelInSleepingArea,
        brightnessInSleepingArea: value.brightnessInSleepingArea,
        nutritionScore: value.nutritionScore,
        substanceUseIndicator: value.substanceUseIndicator,
        cognitiveFatigueScore: value.cognitiveFatigueScore,
        caffeineConsumption: value.caffeineConsumption,
        timeZone: value.timeZone,
        sleepAwakeningCount: value.sleepAwakeningCount,
        sleepDuration: value.sleepDuration
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    respiratoryAnalysis: [] | [{
            breathingRate: number;
            co2RetentionEstimate: number;
            apneaHypopneaIndex: number;
            breathConsistency: number;
            oxygenSaturation: number;
            sleepCycleBreathCorrelation: number;
        }];
    microMovementAnalysis: [] | [{
            movementBurstFrequency: number;
            totalSleepMovementIndex: number;
            restlessnessScore: number;
            sleepStageMovementCorrelation: number;
            movementIntensityProfile: number;
        }];
    sleepArchitectureAnalysis: [] | [{
            sleepStageTransitions: Array<bigint>;
            sleepStageDurationAnalysis: Array<number>;
            sleepStageDistribution: Array<number>;
            sleepCycleCount: bigint;
        }];
    hrvAnalysis: [] | [{
            fragmentIndex: number;
            meanHrv: number;
            sdnn: number;
            circadianRhythmPhase: number;
            sleepStageHrvCorrelation: number;
            rmssd: number;
        }];
}): {
    respiratoryAnalysis?: {
        breathingRate: number;
        co2RetentionEstimate: number;
        apneaHypopneaIndex: number;
        breathConsistency: number;
        oxygenSaturation: number;
        sleepCycleBreathCorrelation: number;
    };
    microMovementAnalysis?: {
        movementBurstFrequency: number;
        totalSleepMovementIndex: number;
        restlessnessScore: number;
        sleepStageMovementCorrelation: number;
        movementIntensityProfile: number;
    };
    sleepArchitectureAnalysis?: {
        sleepStageTransitions: Array<bigint>;
        sleepStageDurationAnalysis: Array<number>;
        sleepStageDistribution: Array<number>;
        sleepCycleCount: bigint;
    };
    hrvAnalysis?: {
        fragmentIndex: number;
        meanHrv: number;
        sdnn: number;
        circadianRhythmPhase: number;
        sleepStageHrvCorrelation: number;
        rmssd: number;
    };
} {
    return {
        respiratoryAnalysis: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.respiratoryAnalysis)),
        microMovementAnalysis: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.microMovementAnalysis)),
        sleepArchitectureAnalysis: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.sleepArchitectureAnalysis)),
        hrvAnalysis: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.hrvAnalysis))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    musician: null;
} | {
    doctor: null;
} | {
    other: string;
} | {
    teacher: null;
} | {
    designer: null;
} | {
    nurse: null;
} | {
    student: null;
} | {
    softwareEngineer: null;
} | {
    artist: null;
} | {
    scientist: null;
}): {
    __kind__: "musician";
    musician: null;
} | {
    __kind__: "doctor";
    doctor: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "teacher";
    teacher: null;
} | {
    __kind__: "designer";
    designer: null;
} | {
    __kind__: "nurse";
    nurse: null;
} | {
    __kind__: "student";
    student: null;
} | {
    __kind__: "softwareEngineer";
    softwareEngineer: null;
} | {
    __kind__: "artist";
    artist: null;
} | {
    __kind__: "scientist";
    scientist: null;
} {
    return "musician" in value ? {
        __kind__: "musician",
        musician: value.musician
    } : "doctor" in value ? {
        __kind__: "doctor",
        doctor: value.doctor
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "teacher" in value ? {
        __kind__: "teacher",
        teacher: value.teacher
    } : "designer" in value ? {
        __kind__: "designer",
        designer: value.designer
    } : "nurse" in value ? {
        __kind__: "nurse",
        nurse: value.nurse
    } : "student" in value ? {
        __kind__: "student",
        student: value.student
    } : "softwareEngineer" in value ? {
        __kind__: "softwareEngineer",
        softwareEngineer: value.softwareEngineer
    } : "artist" in value ? {
        __kind__: "artist",
        artist: value.artist
    } : "scientist" in value ? {
        __kind__: "scientist",
        scientist: value.scientist
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n47(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ModuleProgress>): Array<ModuleProgress> {
    return value.map((x)=>from_candid_ModuleProgress_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Intervention>): Array<Intervention> {
    return value.map((x)=>from_candid_Intervention_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SleepEstimatorRun>): Array<SleepEstimatorRun> {
    return value.map((x)=>from_candid_SleepEstimatorRun_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NormalizedSleepInput>): Array<NormalizedSleepInput> {
    return value.map((x)=>from_candid_NormalizedSleepInput_n35(_uploadFile, _downloadFile, x));
}
function to_candid_AdvancedMetrics_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdvancedMetrics): _AdvancedMetrics {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_ExtendedMentalHealthProfile_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExtendedMentalHealthProfile): _ExtendedMentalHealthProfile {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Intervention_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Intervention): _Intervention {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_ModuleProgress_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModuleProgress): _ModuleProgress {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_NormalizedSleepInput_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NormalizedSleepInput): _NormalizedSleepInput {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_Profession_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profession): _Profession {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_SleepEstimatorRun_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SleepEstimatorRun): _SleepEstimatorRun {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    futureGoals: Array<LifeGoal>;
    displayName: string;
    profession: Profession;
    anonymousMode: boolean;
    gender: bigint;
    consentGiven: boolean;
    timeZone: string;
}): {
    age: [] | [bigint];
    futureGoals: Array<_LifeGoal>;
    displayName: string;
    profession: _Profession;
    anonymousMode: boolean;
    gender: bigint;
    consentGiven: boolean;
    timeZone: string;
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        futureGoals: value.futureGoals,
        displayName: value.displayName,
        profession: to_candid_Profession_n50(_uploadFile, _downloadFile, value.profession),
        anonymousMode: value.anonymousMode,
        gender: value.gender,
        consentGiven: value.consentGiven,
        timeZone: value.timeZone
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: bigint;
    endTime?: bigint;
    name: string;
    type: string;
    progress: number;
    notes: string;
}): {
    id: string;
    startTime: bigint;
    endTime: [] | [bigint];
    name: string;
    type: string;
    progress: number;
    notes: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        name: value.name,
        type: value.type,
        progress: value.progress,
        notes: value.notes
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moduleId: string;
    isCompleted: boolean;
    artifacts?: Array<string>;
    currentStep: bigint;
    lastSaved: bigint;
}): {
    moduleId: string;
    isCompleted: boolean;
    artifacts: [] | [Array<string>];
    currentStep: bigint;
    lastSaved: bigint;
} {
    return {
        moduleId: value.moduleId,
        isCompleted: value.isCompleted,
        artifacts: value.artifacts ? candid_some(value.artifacts) : candid_none(),
        currentStep: value.currentStep,
        lastSaved: value.lastSaved
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    summaryMetrics: SleepMetrics;
    runTimestamp: bigint;
    riskIndicators: RiskIndicator;
    audioAnalysisMetadata?: {
        duration: number;
        audioFeatureVector: number;
        sampleRate: bigint;
    };
    optimizationSuggestions: Array<string>;
    notes?: string;
    normalizedDailyInputs: Array<NormalizedSleepInput>;
    sensorDataUsed?: {
        accelerometer: boolean;
        heartRateMonitor: boolean;
        breathingSensor: boolean;
        temperatureSensor: boolean;
    };
    daysAnalyzed: bigint;
    advancedMetrics?: AdvancedMetrics;
    dataFormatVersion: string;
}): {
    summaryMetrics: _SleepMetrics;
    runTimestamp: bigint;
    riskIndicators: _RiskIndicator;
    audioAnalysisMetadata: [] | [{
            duration: number;
            audioFeatureVector: number;
            sampleRate: bigint;
        }];
    optimizationSuggestions: Array<string>;
    notes: [] | [string];
    normalizedDailyInputs: Array<_NormalizedSleepInput>;
    sensorDataUsed: [] | [{
            accelerometer: boolean;
            heartRateMonitor: boolean;
            breathingSensor: boolean;
            temperatureSensor: boolean;
        }];
    daysAnalyzed: bigint;
    advancedMetrics: [] | [_AdvancedMetrics];
    dataFormatVersion: string;
} {
    return {
        summaryMetrics: value.summaryMetrics,
        runTimestamp: value.runTimestamp,
        riskIndicators: value.riskIndicators,
        audioAnalysisMetadata: value.audioAnalysisMetadata ? candid_some(value.audioAnalysisMetadata) : candid_none(),
        optimizationSuggestions: value.optimizationSuggestions,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        normalizedDailyInputs: to_candid_vec_n58(_uploadFile, _downloadFile, value.normalizedDailyInputs),
        sensorDataUsed: value.sensorDataUsed ? candid_some(value.sensorDataUsed) : candid_none(),
        daysAnalyzed: value.daysAnalyzed,
        advancedMetrics: value.advancedMetrics ? candid_some(to_candid_AdvancedMetrics_n61(_uploadFile, _downloadFile, value.advancedMetrics)) : candid_none(),
        dataFormatVersion: value.dataFormatVersion
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sleepConsistencyScore: number;
    screenTimeBeforeBed: number;
    sleepQualityRating: bigint;
    bedtime: bigint;
    sleepLatency: number;
    stressLevel: bigint;
    napTime?: bigint;
    environmentalQualityScore: number;
    sleepPreparationRating: bigint;
    napDuration?: bigint;
    physicalActivityIntensity: bigint;
    wakeTime: bigint;
    emotionalStateScore: bigint;
    noiseLevelInSleepingArea: bigint;
    brightnessInSleepingArea: bigint;
    nutritionScore: number;
    substanceUseIndicator: boolean;
    cognitiveFatigueScore: bigint;
    caffeineConsumption: number;
    timeZone: string;
    sleepAwakeningCount: bigint;
    sleepDuration: number;
}): {
    sleepConsistencyScore: number;
    screenTimeBeforeBed: number;
    sleepQualityRating: bigint;
    bedtime: bigint;
    sleepLatency: number;
    stressLevel: bigint;
    napTime: [] | [bigint];
    environmentalQualityScore: number;
    sleepPreparationRating: bigint;
    napDuration: [] | [bigint];
    physicalActivityIntensity: bigint;
    wakeTime: bigint;
    emotionalStateScore: bigint;
    noiseLevelInSleepingArea: bigint;
    brightnessInSleepingArea: bigint;
    nutritionScore: number;
    substanceUseIndicator: boolean;
    cognitiveFatigueScore: bigint;
    caffeineConsumption: number;
    timeZone: string;
    sleepAwakeningCount: bigint;
    sleepDuration: number;
} {
    return {
        sleepConsistencyScore: value.sleepConsistencyScore,
        screenTimeBeforeBed: value.screenTimeBeforeBed,
        sleepQualityRating: value.sleepQualityRating,
        bedtime: value.bedtime,
        sleepLatency: value.sleepLatency,
        stressLevel: value.stressLevel,
        napTime: value.napTime ? candid_some(value.napTime) : candid_none(),
        environmentalQualityScore: value.environmentalQualityScore,
        sleepPreparationRating: value.sleepPreparationRating,
        napDuration: value.napDuration ? candid_some(value.napDuration) : candid_none(),
        physicalActivityIntensity: value.physicalActivityIntensity,
        wakeTime: value.wakeTime,
        emotionalStateScore: value.emotionalStateScore,
        noiseLevelInSleepingArea: value.noiseLevelInSleepingArea,
        brightnessInSleepingArea: value.brightnessInSleepingArea,
        nutritionScore: value.nutritionScore,
        substanceUseIndicator: value.substanceUseIndicator,
        cognitiveFatigueScore: value.cognitiveFatigueScore,
        caffeineConsumption: value.caffeineConsumption,
        timeZone: value.timeZone,
        sleepAwakeningCount: value.sleepAwakeningCount,
        sleepDuration: value.sleepDuration
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    respiratoryAnalysis?: {
        breathingRate: number;
        co2RetentionEstimate: number;
        apneaHypopneaIndex: number;
        breathConsistency: number;
        oxygenSaturation: number;
        sleepCycleBreathCorrelation: number;
    };
    microMovementAnalysis?: {
        movementBurstFrequency: number;
        totalSleepMovementIndex: number;
        restlessnessScore: number;
        sleepStageMovementCorrelation: number;
        movementIntensityProfile: number;
    };
    sleepArchitectureAnalysis?: {
        sleepStageTransitions: Array<bigint>;
        sleepStageDurationAnalysis: Array<number>;
        sleepStageDistribution: Array<number>;
        sleepCycleCount: bigint;
    };
    hrvAnalysis?: {
        fragmentIndex: number;
        meanHrv: number;
        sdnn: number;
        circadianRhythmPhase: number;
        sleepStageHrvCorrelation: number;
        rmssd: number;
    };
}): {
    respiratoryAnalysis: [] | [{
            breathingRate: number;
            co2RetentionEstimate: number;
            apneaHypopneaIndex: number;
            breathConsistency: number;
            oxygenSaturation: number;
            sleepCycleBreathCorrelation: number;
        }];
    microMovementAnalysis: [] | [{
            movementBurstFrequency: number;
            totalSleepMovementIndex: number;
            restlessnessScore: number;
            sleepStageMovementCorrelation: number;
            movementIntensityProfile: number;
        }];
    sleepArchitectureAnalysis: [] | [{
            sleepStageTransitions: Array<bigint>;
            sleepStageDurationAnalysis: Array<number>;
            sleepStageDistribution: Array<number>;
            sleepCycleCount: bigint;
        }];
    hrvAnalysis: [] | [{
            fragmentIndex: number;
            meanHrv: number;
            sdnn: number;
            circadianRhythmPhase: number;
            sleepStageHrvCorrelation: number;
            rmssd: number;
        }];
} {
    return {
        respiratoryAnalysis: value.respiratoryAnalysis ? candid_some(value.respiratoryAnalysis) : candid_none(),
        microMovementAnalysis: value.microMovementAnalysis ? candid_some(value.microMovementAnalysis) : candid_none(),
        sleepArchitectureAnalysis: value.sleepArchitectureAnalysis ? candid_some(value.sleepArchitectureAnalysis) : candid_none(),
        hrvAnalysis: value.hrvAnalysis ? candid_some(value.hrvAnalysis) : candid_none()
    };
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "musician";
    musician: null;
} | {
    __kind__: "doctor";
    doctor: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "teacher";
    teacher: null;
} | {
    __kind__: "designer";
    designer: null;
} | {
    __kind__: "nurse";
    nurse: null;
} | {
    __kind__: "student";
    student: null;
} | {
    __kind__: "softwareEngineer";
    softwareEngineer: null;
} | {
    __kind__: "artist";
    artist: null;
} | {
    __kind__: "scientist";
    scientist: null;
}): {
    musician: null;
} | {
    doctor: null;
} | {
    other: string;
} | {
    teacher: null;
} | {
    designer: null;
} | {
    nurse: null;
} | {
    student: null;
} | {
    softwareEngineer: null;
} | {
    artist: null;
} | {
    scientist: null;
} {
    return value.__kind__ === "musician" ? {
        musician: value.musician
    } : value.__kind__ === "doctor" ? {
        doctor: value.doctor
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "teacher" ? {
        teacher: value.teacher
    } : value.__kind__ === "designer" ? {
        designer: value.designer
    } : value.__kind__ === "nurse" ? {
        nurse: value.nurse
    } : value.__kind__ === "student" ? {
        student: value.student
    } : value.__kind__ === "softwareEngineer" ? {
        softwareEngineer: value.softwareEngineer
    } : value.__kind__ === "artist" ? {
        artist: value.artist
    } : value.__kind__ === "scientist" ? {
        scientist: value.scientist
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<NormalizedSleepInput>): Array<_NormalizedSleepInput> {
    return value.map((x)=>to_candid_NormalizedSleepInput_n59(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
